DROP TABLE IF EXISTS "manga";


CREATE TABLE IF NOT EXISTS "manga" (
    "id"        SERIAL PRIMARY KEY NOT NULL ,
    "nom_japonais"    VARCHAR(85) NOT NULL,
    "nom_français"    VARCHAR(82) NOT NULL,
    "genres"          VARCHAR(18) NOT NULL,
    "lecture_manga"   VARCHAR(65),
    "visionage_anime" VARCHAR(36)
);

INSERT INTO "manga"("id","nom_japonais","nom_français","genres","lecture_manga","visionage_anime") VALUES
(1,'&','& (And)','Josei','44 (finie)','-'),
(2,'10 Count','Ten count','Josei','48 (fini)','-'),
(3,'100% Love Gauge/Love Gauge 100%','100% Love Gauge/Love Gauge 100%','Yaoi/Webtoon','7 (finie)',NULL),
(4,'10th','10th You and I fell in love with the same person','Shojo','11 (finie)','-'),
(5,'20 Nen Buri ni Netemitara','20 Nen Buri ni Netemitara','Yaoi','12 (finie)','-'),
(6,'20th Century Boys','Nijuuseiki Shounen','Seinen','1 tome','-'),
(7,'25JI, AKASAKA DE','AT 25:00, IN AKASAKA','Yaoi','Vol 2 (en attente vol 3 )','-'),
(8,'2ban-me no Alpha','2ban-me no Alpha','Yaoi','7 (finie)',NULL),
(9,'3 Way Return','3 Way Return','Josei/BL','6 (finie)',NULL),
(10,'3-gatsu no Lion  / Sangatsu no Lion','March comes in like a lion','Seinen','-','1 saison (finie)'),
(11,'37°C Spirits','37°C Spirits','Yaoi','4 (finie)',NULL),
(12,'3D Kanojo - Real Girl','3D Girlfriend','Shojo','-','2 saisons (finie)'),
(13,'5-toubun no Hanayome','The Quintessential Quintuplets','Shonen','-','1 saison'),
(14,'6 lovers','6 lovers','Josei','-','OAV (finie)'),
(15,'A closer look','A closer look','BL','1 (en cours)','-'),
(16,'A painter behind the curtain','A painter behind the curtain','Yaoi/Webtoon','75 (finie)',NULL),
(17,'A silent voice','A Silent Voice','Shojo','62 (finie)','-'),
(18,'A sleeping man and a loving man','A sleeping man and a loving man','Yaoi','oneshot',NULL),
(19,'A Thousand Cranes','A Thousand Cranes','Yaoi/Webtoon','35 (finie)',NULL),
(20,'A Whisker Away','Loin de moi, près de toi','Film','-','film (fini)'),
(21,'Abarenbo honey','Abarenbo honey','Yaoi','13 (finie)',NULL),
(22,'Acid Town','Acid Town','Seinen/BL','51 (en cours)','-'),
(23,'Adam no Rokkotsu','Adam no Rokkotsu','Yaoi','13 (finie)',NULL),
(24,'Aggretsuko','Aggretsuko','Seinen','-','1 saison (en cours)'),
(25,'Aho Ero','Aho Ero','Josei/BL','5 (fine)',NULL),
(26,'Ai Sei','Ai Sei','Yaoi','1 (finie)',NULL),
(27,'ai wo shitteiru','ai wo shitteiru','Seinen','(5 finie)',NULL),
(28,'Aien Catharsis','Aien Catharsis','Josei','6 (finie)','-'),
(29,'Aioi Focus','Aioi Focus','Yaoi','5 (finie)',NULL),
(30,'Aiou Futari','Aiou Futari','Yaoi','5 (fine)',NULL),
(31,'Aka no Theatre','Aka no Theatre','Josei/BL','6 (finie)',NULL),
(32,'Akagami no Shirayuki-hime','Shirayuki aux cheveux rouges','Shojo','-','24 (finie)'),
(33,'Akai Ito no Shikkou Yuuyo','Le fil du destin','Josei/BL','5 (finie)',NULL),
(34,'Akakute Amai','Akakute Amai','Josei/BL','7 (finie)','-'),
(35,'Akatsuki no Yona','Yona, Princesse de l''Aube','Shojo','234 (en cours)','1 saison (finie)'),
(36,'Akihabara Fall In Love','Akihabara Fall In Love','Josei/BL','5 (finie)','-'),
(37,'Akira','Akira','Seinen','-','Film'),
(38,'Akkun to Kanojo','Akkun and His Girlfriend','Shojo','-','1 saison (à finir)'),
(39,'Akuheki','Akuheki','Josei/BL','3 (en cours)',NULL),
(40,'Albator','Albator','Film','-','Film OAV'),
(41,'All about lust','All about lust','Yaoi/Webtoon','60 (finie)',NULL),
(42,'Alpha no Ie no Ko','Alpha no Ie no Ko','Joseil/BL','6 (finie)',NULL),
(43,'Amaama to Inazuma','Amaama to Inazuma','Seinen','-','1 saison (finie)'),
(44,'Amaenbo Honey','Amaenbo Honey','Yaoi','5 (finie)',NULL),
(45,'Ameagari no Bokura ni Tsuite','Ameagari no Bokura ni Tsuite','Yaoi','12 (finie)',NULL),
(46,'Ameiro Paradox','Ameiro Paradox','Josei/BL','26 (en cours)','-'),
(47,'Anata ga Shite Kurenakutemo','Corps Solitaires /','Josei','80 (en cours)','-'),
(48,'Angel beats!','Angel beats!','Seinen','-','1 saison (finie)'),
(49,'Ani ga Kareshi de Gomen','Ani ga Kareshi de Gomen','Shojo','24 (finie)','-'),
(50,'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.','Anohana','Shonen','-','1 saison (finie)'),
(51,'Ansatsu Kyoushitsu','Assasination classroom','Shonen','-','2 saisons (finie)'),
(52,'Anti-Alpha','Anti-Alpha','Yaoi/Webtoon','7 (en cours)',NULL),
(53,'Anti-Romance','Anti-Romance','Josei/BL','8 (en cours)','-'),
(54,'Ao Haru Ride','Blue Spring Ride','Shojo','-','1 saison (finie)'),
(55,'Ao Ni Naku','Ao Ni Naku','Josei/BL','8 (finie)','-'),
(56,'Ao no Futsumashi','Blue exorcist','Shonen','-',NULL),
(57,'Ao no Hana Utsuwa no Mori','The Blue Flower and The Container Forest','Josei','3 (en cours- scan abandonné?)','-'),
(58,'Araburu Kisetsu no Otome-domo yo','O Maidens in Your Savage Season','Shojo','-','1 saison (finie)'),
(59,'Arakawa under the bridge','Arakawa under the bridge','Josei','-','2 saisons (finie)'),
(60,'Arashi no Ato','After the storm','Josei/BL','6 (finie)','-'),
(61,'Arima-san wa omega ni naritai','Arima-san wa omega ni naritai','Yaoi','S2 (4 en cours)',NULL),
(62,'Around 30 dakedo, Hatsukoi desu','I''m around thirty and finally in love','Josei','60 (finie)','-'),
(63,'Asa to Mitya','Asa to Mitya','Shojo/BL','10 (finie)','-'),
(64,'Asatte ni Kiss','Asatte ni Kiss','Josei/BL','6 (finie)','-'),
(65,'Ase to Sekken','Sweat and soap','Seinen','97 (finie)','-'),
(66,'Ashita Niji ga denakute mo','Ashita Niji ga denakute mo','Josei/BL','7 (finie)',NULL),
(67,'Ashita wa Docchi da!','Ashita wa Docchi da!','Shojo/BL','32 (en cours)','ch23/30'),
(68,'Asper Kanojo','Asper Kanojo','Seinen','48 (en cours)','-'),
(69,'Atsumori-kun no Oyome-san (←Mitei)','Atsumori-kun''s Bride (← Pending)','Shojo','25 (finie)','-'),
(70,'Azami','Azami','Josei/BL','One shot',NULL),
(71,'Back Stage','Back Stage','Yaoi','7 (en cours)',NULL),
(72,'Bad Company','Bad Company','Yaoi','(en cours) 1 tome',NULL),
(73,'Bakana Inuhodo Itooshii','Bakana Inuhodo Itooshii','Josei/BL','5 (finie)',NULL),
(74,'Bakemono no Hanayome','Bakemono no Hanayome','Yaoi','6 (finie)',NULL),
(75,'Bakeneko Katatte Sourou','Bakeneko Katatte Sourou','Shojo/BL','8 (finie)',NULL),
(76,'Banana fish','Banana Fish','Shojo','-','1 saison ( à finir)'),
(77,'Barakamon','Barakamon','Shonen','-','1 saison (finie)'),
(78,'Baraou no Souretsu','Requiem of the Rose King','Shojo','Vol 13 (60 en cours)','1 saison'),
(79,'Basilisk','Basilisk','Seinen','-','2 saisons (finie)'),
(80,'Beastars','Beastars','Shonen','-','1 saison (2 saison 2021)'),
(81,'Bena','Bena','Yaoi','3 tome (en cours)',NULL),
(82,'Berserk','Berserk','Seinen','364 (finie)','1 saison (?)'),
(83,'Berserk serie 2016','Berserk serie 2016','Seinen','-','2 saisons (en cours)'),
(84,'Bishoujo Senshi Sailor Moon','Sailor Moon','Shojo','-','1 saison (regardé jeune)'),
(85,'BJ Alex','BJ Alex','Yaoi/Webtoon','89 (finie)',NULL),
(86,'Black Bullet','Black Bullet','Shonen','-','13 (finie)'),
(87,'Black Clover','Black Clover','Shonen',NULL,NULL),
(88,'Black Mirror','Black Mirror','Yaoi/Webtoon','62 (finie)',NULL),
(89,'Blanc','Blanc','Shojo/BL','11 (finie)',NULL),
(90,'Bleach','Bleach','Shonen','-','16 saisons (finie)'),
(91,'Blend S','Blend S','Seinen','-','1 saison (finie)'),
(92,'Blood +','Blood +','Seinen','-','1 saison (finie)'),
(93,'Blood Bank','Blood Bank','Yaoi/Webtoon','61 (finie)',NULL),
(94,'Blood Link','Blood Link','Yaoi/Webtoon','135 (finie)',NULL),
(95,'Blue Lust','Blue Lust','Josei/BL','14 (finie)','-'),
(96,'Blue moment','Blue moment','Shojo/BL','5 (finie)',NULL),
(97,'Blue Period','Blue Period','Seinen','-','5 (en cours)'),
(98,'Blue sky complex','Blue sky complex','Josei/BL','34 (en cours) 356raw',NULL),
(99,'Blue! Blue! Blue!','Blue! Blue! Blue!','Shojo/BL','5 (finie)','-'),
(100,'Boku Dake ga Inai Machi','Erased','Seinen','-','1 saison (finie)'),
(101,'Boku no Hero Academia','My Hero Academia','Shonen','307 (en cours)','4 Saisons (en cours)'),
(102,'Boku no Hero Academia : Heroes Rising','My Hero Academia : Heroes Rising','Film','-','Film OAV'),
(103,'Boku no Omawari-san','My Pretty Policeman','Josei/BL','13  Vol 3 chap 3 (en cours)','-'),
(104,'Boku no Papa to Papa no Hanashi','Boku no Papa to Papa no Hanashi','Yaoi','6 (finie)',NULL),
(105,'Boku wa imouto ni Koi wo Suru','Secret Sweethearts','Shojo','-','Film'),
(106,'Boku wo Warui Ko ni Shite','Boku wo Warui Ko ni Shite','Josei/BL','5 (finie)',NULL),
(107,'Bokura ga Koi wo Ushinau Riyuu','Bokura ga Koi wo Ushinau Riyuu','Josei/BL','6 (finie)','-'),
(108,'Bokura no Koi wo Kimi wa Shiranai','Bokura no Koi wo Kimi wa Shiranai','Josei/BL','5 (finie)',NULL),
(109,'Bokura wa Mada Hyougaki no Tochuu','Bokura wa Mada Hyougaki no Tochuu','Josei','4 (finie)','-'),
(110,'Bokura wa Nando mo Koi o suru','Bokura wa Nando mo Koi o suru','Yaoi','6 (finie)',NULL),
(111,'Bokura wa Unmei Janai','Bokura wa Unmei Janai','Yaoi','6 ( finie)',NULL),
(112,'Bokutachi wa Benkyou ga Dekinai','We Never Learn','Shonen','-','2 saison (finie)'),
(113,'Born to be on air!','Born to be on air','Seinen','-','1 saison (?)'),
(114,'Boruto','Boruto','Shonen','-','1 saison (à finir) (en cours)'),
(115,'Boy Meets Maria','Boy Meets Maria','Shojo/BL','6 (finie)',NULL),
(116,'Boys of the Dead','Boys of the Dead','Seinen','4 (en cours)','-'),
(117,'Brothers','Brothers','Shojo/BL','12 (finie)','-'),
(118,'Brothers +','Brothers +','Shojo/BL','19 (en cours)','-'),
(119,'Brutal: Satsujin Kansatsukan No Kokuhaku','Brutal: Satsujin Kansatsukan No Kokuhaku','Seinen','11 (en cours)',NULL),
(120,'Bungo Stray Dogs','Bungo Stray Dogs','Seinen','-','3 (saisons)'),
(121,'Burai-an','Burai-an','Yaoi','5 (finie)',NULL),
(122,'Business Like','Business Like','Shojo/BL','10 (finie)','-'),
(123,'By My Side','By My Side','Josei/BL','6 ( finie)',NULL),
(124,'Call','Call','Josei/BL','7 (finie?? extras?)',NULL),
(125,'Called Game','Called Game','Shojo','14 Vol 4 ( en cours)','-'),
(126,'Canis Dear Hatter','Canis Dear Hatter','Yaoi','2 tome (finie)',NULL),
(127,'Canis Dear Mr. Rain','Canis Dear Mr. Rain','Yaoi','1 tome (finie)',NULL),
(128,'Captain Tsubasa','Super Campeones','Shonen','-','1 saison (regardé jeune)'),
(129,'Caste Heaven','Caste Heaven','Shojo/BL','38 (en cours)','-'),
(130,'Chainsaw man','Chainsaw man','Shonen','113 (en cours)','(à venir)'),
(131,'Change World','Change World','Josei/BL','8 (finie)',NULL),
(132,'Cherish','Cherish','Josei','3 (fini)','-'),
(133,'Cherry Blossoms after winter','Cherry Blossoms after winter','Yaoi/Webtoon','146 (finie)',NULL),
(134,'Chi no Wadachi','Les liens du sang','Seinen','20 (en cours)','-'),
(135,'Chicken Heart Serenade','Chicken Heart Serenade','Yaoi','6 (finie)',NULL),
(136,'Chihayafuru','Chihayafuru','Shojo','244 (finie)','-'),
(137,'Childhood Friend Irony','Childhood Friend Irony','Josei/BL','5 (finie)','-'),
(138,'Chiruran - Shinsengumi Requiem','Chiruran - Shinsengumi Requiem','Shonen','Vol 1 (en cours)',NULL),
(139,'Chobits','Chobits','Shojo','-','27 (finie)'),
(140,'Choco Strawberry Vanilla','Choco Strawberry Vanilla','Josei/BL','6 (finie)','-'),
(141,'Chou to Hana no Kankeisei','Chou to Hana no Kankeisei','Yaoi','9 (finie)',NULL),
(142,'Clannad','Clannad','Shonen','-','2 saisons (finie) Visual Novel'),
(143,'Code :','Code :','BL','5 (finie)','-'),
(144,'Code Geass : Hangyaku no Lelouch','Code Geass : Lelouch of the Rebellion','Mecha','-','2 saisons'),
(145,'Coffee and Vanilla','Coffee and Vanilla','Josei','13 (pas trop aimé)',NULL),
(146,'Collar Kiss','Collar Kiss','Yaoi/Webtoon','9 (finie)',NULL),
(147,'Color Recipe','Color Recipe','Josei/BL','11 (finie)','-'),
(148,'Come to Hand','Come to Hand','Shojo/BL','5 (finie)','-'),
(149,'Contrast','Contrast','Yaoi','10 (finie)',NULL),
(150,'Cowboy bebop','Cowboy Bebop','Seinen','-','1 saison (finie)'),
(151,'Coyote','Coyote','Josei/BL','15 (en cours) Vol 3 je crois','-'),
(152,'Cupid ni Rakurai','Cupid ni Rakurai','Yaoi','2 tomes (finie)',NULL),
(153,'Daifuku-chan to Ouji-sama','Daifuku-chan to Ouji-sama','Shojo','9 (en cours)','-'),
(154,'Dakaretai Otoko 1-i ni Odosarete Imasu','DAKAICHI -My number 1','Josei','-','1 saison'),
(155,'Dame na Watashi ni Koishite Kudasai','Dame na Watashi ni Koishite Kudasai','Shojo','40 finie)','-'),
(156,'Dame na Watashi ni Koishite Kudasai Returns','Dame na Watashi ni Koishite Kudasai Returns','Shojo','18 (en cours)','-'),
(157,'Dandara Gohan','Dandara Gohan','Shonen','2 (en cours)',NULL),
(158,'Dangerous Convenience Store','Dangerous Convenience Store','Yaoi/Webtoon','84 (en cours)',NULL),
(159,'Danna ga Nani wo Itteiru ka Wakaranai Ken','I Can''t Understand What My Husband Is Saying','Seinen','-','2 saisons'),
(160,'Dark Heaven','Dark Heaven','Yaoi/Webtoon','83 (finie)',NULL),
(161,'Darker than BLACK','Darker than BLACK','Seinen','-','5 (en cours)'),
(162,'Darling Give me a break!','Darling Give me a break!','Yaoi','1 tome (finie)',NULL),
(163,'Darling in the Franxx','Darling in the Franxx','Shonen','-','1 saison (finie)'),
(164,'Dead Company','Dead Company','Seinen','4 (en cours)',NULL),
(165,'Dear Benjamin','Dear Benjamin','Yaoi/Webtoon','45 (finie)',NULL),
(166,'Dear Door','Dear Door','Yaoi/Webtoon','123 (en cours) 20 extra',NULL),
(167,'Dear Gene','Dear Gene','Yaoi','Vol 1 (finie)','-'),
(168,'Dear Signal','Dear Signal','Shojo/BL','5 (finie)',NULL),
(169,'Death Note','Death Note','Shonen','-','1 saison (finie)'),
(170,'December Rain','December Rain','Yaoi/Webtoon','51 (finie)',NULL),
(171,'Deen my Love','Deen my Love','Yaoi','4 (finie)',NULL),
(172,'Define the relationship','Define the relationship','Yaoi/Webtoon','58 (en cours)',NULL),
(173,'Dekiai Nante Mitomemasen!','Dekiai Nante Mitomemasen!','Yaoi','5 (finie)',NULL),
(174,'Dekiai Yakuza ni wa Amayakasarenai!','Dekiai Yakuza ni wa Amayakasarenai!','Shojo','4 (en cours)','-'),
(175,'Dekinai Futari','Dekinai Futari','Josei','19 (suivie)','-'),
(176,'Dekoboko Bittersweet Days','Dekoboko Bittersweet Days','Yaoi','6( finie)',NULL),
(177,'Dekoboko Sugar Days','Dekoboko Sugar Days','Yaoi','6( finie)',NULL),
(178,'Demi-chan wa Katarita','Freaky girls','Seinen','-','1 saison'),
(179,'Derail','Derail','Josei/BL','2 (en cours)',NULL),
(180,'Despicable','Despicable','Josei/BL','5 (finie)','-'),
(181,'Devils Line','Devils'' Line','Seinen','69 (finie)','1 saison 12 (finie)'),
(182,'Divorce Me, Mr. Alpha','Divorce Me, Mr. Alpha','Yaoi','8 (en cours)',NULL),
(183,'Don’t be shy','Karasugaoka Don''t Be Shy!!','BL','6 (finie)','-'),
(184,'Don’t be shy 2','Karasugaoka Don''t Be Shy!!  2','BL','6 (finie)','-'),
(185,'Doronuma','Doronuma','Josei/BL','8 (finie)','-'),
(186,'Double suicide','Double suicide','Shonen ai','5 (finie) ?',NULL),
(187,'Doubt','Doubt','Seinen','20 (finie)',NULL),
(188,'Doukyonin wa Hiza, Tokidoki, Atama no Ue.','My roommate is a cat','Shojo','-','1 saison (finie)'),
(189,'Doukyuusei','Doukyuusei','Shojo/BL','10 (finie)','-'),
(190,'Dousei Yankee Akamatsu Seven','Dousei Yankee Akamatsu Seven','Yaoi','finie??',NULL),
(191,'Doushitemo Furetakunai','Doushitemo Furetakunai','Josei','7 (fini)','-'),
(192,'Doutei ni Ai Nante Sakebenai!','Doutei ni Ai Nante Sakebenai!','Josei/BL','4 (finie)','-'),
(193,'Dr. Stone','Dr. Stone','Shonen','-','1 saison, 2 saison 2021'),
(194,'Dragon Ball','Dragon Ball','Shonen','-','1 saison (regardé jeune)'),
(195,'Dragon Quest : Dai no Daibouken','Dragon Quest - La quête de Dai','Shonen','-','1 saison (à finir)'),
(196,'Dream Land','Dream Land','Josei/BL','5 (finie)','-'),
(197,'Dumbbell Nan-Kilo Moteru?','Dumbbell : Combien tu peux soulever ?','Shonen','-','1 saison (finie?)'),
(198,'ef : A Tale of Melodies','ef : A Tale of Melodies','Shonen','-','1 saison (finie) Visual Novel'),
(199,'ef : a tale of memories','ef : a tale of memories','Shonen','-','1 saison (finie) Visual Novel'),
(200,'Elfen Lied','Elfen Lied','Seinen','-','1 saison (finie)'),
(201,'Endou-kun no Jikken Note','Endou-kun no Jikken Note','Shojo','7 (en cours) abandonné','-'),
(202,'Endou-kun no Kansatsu Nikki','Endou-kun no Kansatsu Nikki','Shojo','4 (finie)','-'),
(203,'Engage','Engage','Yaoi','2 (en cours)',NULL),
(204,'Enn Enn no Shouboutai','Fire Force','Shonen','-','2 saisons (en cours)'),
(205,'Erito Ω Wa Yoru ni Oborete','Erito Ω Wa Yoru ni Oborete','Yaoi','23 (en cours)',NULL),
(206,'Escape journey','Escape journey','Josei','17 (fini)','-'),
(207,'Evangelion','Evangelion','Seinen','-','Film'),
(208,'Evangelion : 1.0 You Are (Not) Alone','Evangelion : 1.0 You Are (Not) Alone','Film','-','Film OAV'),
(209,'Evangelion : 2.22 You Can (Not) Advance','Evangelion : 2.22 You Can (Not) Advance','Film','-','Film OAV'),
(210,'Evangelion: 3.0 You Can (Not) Redo','Evangelion: 3.0 You Can (Not) Redo','Film','-','Film OAV ( à regarder prochainement)'),
(211,'Everyday is a good day','Everyday is a good day','Shojo/Boy''s Love','4 (finie)','-'),
(212,'Excel saga','Excel saga','Seinen','-','1 saison (à finir)'),
(213,'Fake Fact Lips','Fake Fact Lips','Yaoi','6 (finie)',NULL),
(214,'Fangs','Fangs','Josei/BL','9 (en cours)','-'),
(215,'Finder no Hyouteki','Viewfinder','Josei/BL','89 (en cours)',NULL),
(216,'Flaver','Flaver','Yaoi','5 (finie)',NULL),
(217,'FMA/ Hagane no Renkinjutsush','Full Metal Alchemist','Shonen','-','finie'),
(218,'Friend Line','Friend Line','Josei/BL','5 (finie)','-'),
(219,'From Heaven Heaven','From Heaven Heaven','Yaoi','1 tome (finie)',NULL),
(220,'Fruits basket','Fruits Basket','Shojo','136 (fini)','2 saison (3 saison 2021)'),
(221,'Fudanshi Kôkô Seikatsu','Fudanshi Koukou Seikatsu','Shojo','-','1 saison (finie)'),
(222,'Fugou Keiji Balance : Unlimited','The Millionaire Detective - Balance: UNLIMITED','Shonen','-','1 saison (finie?)'),
(223,'Fukigen na Kimi to Kimagure na Kiss','Fukigen na Kimi to Kimagure na Kiss','Josei/BL','5 (finie)','-'),
(224,'Fukutsu no Zono','Fukutsu no Zono','Yaoi','5 (finie)',NULL),
(225,'Fumetsu no Anata e','To your eternity','Shonen','-','1 saison (en cours)'),
(226,'Fune wo Amu','The great passage','Seinen','-','1 saison (à finir)'),
(227,'Futari de Papa Hajimemashita','Futari de Papa Hajimemashita','Joseil/BL','6 (finie)',NULL),
(228,'Futari Gurashi','Futari Gurashi','Josei/BL','3 (en cours)',NULL),
(229,'Futari no Lion','Les deux lions','Josei/BL','7,5 (finie)','-'),
(230,'Gake no ue no Ponyo','Ponyo sur la falaise','Film','-','film (fini)'),
(231,'Gakuen Mokushiroku','High school of the dead','Shonen','-','1 saison (finie)'),
(232,'Game - Suit no Sukima','GAME - Entre nos corps','Josei','23 Vol 4(en cours)','-'),
(233,'GAME -IN HIGH SCHOOL-','GAME -IN HIGH SCHOOL-','Josei','3 (en cours)',NULL),
(234,'Gamers!','Gamers!','Shonen','-','1 saison (finie)'),
(235,'Gantz','Gantz','Seinen','-','2 saisons (à finir)'),
(236,'Gantz','Gantz','Shonen','-','1 saison (finie)'),
(237,'Gelateria Supernova','Gelateria Supernova','Josei/BL','11 (finie)','-'),
(238,'Gift','Gift','Yaoi','3 tomes (finie)',NULL),
(239,'Gintama','Gintama','Shonen','-','2 saison ( à finir)'),
(240,'Gintama - Shinyaku Benizakura He','Gintama - Shinyaku Benizakura He','Shonen','-','OAV'),
(241,'Gintama The Final','Gintama The Final','Film','-','film (finie) :('),
(242,'Gisou Furin','Gisou Furin','Josei','23 (en cours mais lent)','-'),
(243,'Given','Given','Shojo/Boy''s Love','50 (en cours) vol 5','1 saison + OAV'),
(244,'Gleipnir','Gleipnir','Seinen','-','1 saison (en cours)'),
(245,'Go Riyou wa Keikaku Teki ni','Je prefere en nature','Josei/BL','6 (finie)','-'),
(246,'Gohoubi wa Shitsuke no Ato','Je prefere que tu sois sage','Josei/BL','5 (finie)','-'),
(247,'Gokinjo monogatari','Gokinjo, une vie de quartier','Shojo/Josei','32 (fini)','1 saison (finie)'),
(248,'Gokushufudō','La voie du tablier','Seinen','76 (en cours)','1 saison (finie)'),
(249,'Golden Kamui','Golden Kamui','Seinen','211 (en cours)','2 saison (en cours)'),
(250,'Goma Shio to Purin','Goma Shio to Purin','Josei','22 (finie)','-'),
(251,'Goodbye Harlequin','Goodbye Harlequin','Yaoi','Vol 1 (finie)',NULL),
(252,'Goodbye Lilac','Goodbye Lilac','Josei/BL','6 (finie)','-'),
(253,'Goodbye to Destiny','Goodbye to Destiny','Yaoi','9 (finie)',NULL),
(254,'Goodbye, Nameless Violin','Goodbye, Nameless Violin','Yaoi','7 (finie)',NULL),
(255,'Gosan no Heart','Gosan no Heart','Shojo/BL','5 (finie)','-'),
(256,'Gosou Omega ha chuu to naku','Gosou Omega ha chuu to naku','Yaoi','5 (finie)',NULL),
(257,'Gozen 2ji Made Kimi no Mono','Gozen 2ji Made Kimi no Mono','Yaoi','5 (en cours)',NULL),
(258,'Gozen 3-ji, Kimi wa Naku','Gozen 3-ji, Kimi wa Naku','Yaoi','5 (finie)',NULL),
(259,'GTO - Great Teacher Onizuka','GTO','Shonen','-','1 saison (finie?)'),
(260,'Guardians of the lamb','Guardians of the lamb','Shojo/Webtoon','119 (en cours)',NULL),
(261,'Gunjin Ryuu Propose 100 Nenmono no Vintage Sex','Gunjin Ryuu Propose 100 Nenmono no Vintage Sex','Josei','3 (en cours)','-'),
(262,'Guro Gyaru ni natta kara Shinyuu to Yatte mita.','Guro Gyaru ni natta kara Shinyuu to Yatte mita.','Josei/BL','41 (en cours)',NULL),
(263,'Hadakeru Kaibutsu','Hadakeru Kaibutsu','BL','10 (en cours)','-'),
(264,'Haikyū!!','Haikyū!!','Shonen','-','1 saison (en cours)'),
(265,'Hajime no Ippo','Ippo le challenger','Shonen','-','(à finir)'),
(266,'Hakidame to Tsuru','Hakidame to Tsuru','Josei/BL','6 (finie)','-'),
(267,'Hako no Naka','Hako no Naka','Yaoi','LN',NULL),
(268,'Hakuouki','Hakuouki','Seinen','-','3 saisons (finie)'),
(269,'Hakuouki Movie 2: Shikon Soukyuu','Hakuouki Movie 2: Shikon Soukyuu','Seinen','-','Film OAV'),
(270,'Half cigarette','Half cigarette','Josei','6 (fini)','-'),
(271,'Hana ni Kuchizuke','Hana ni Kuchizuke','Josei/BL','5 (finie)','-'),
(272,'Hana no Miyako de','Fleur et sens','BL','5 (finie)','-'),
(273,'Hana no Mizo Shiru','Seule la fleur sait','Josei/BL','12 (finie)','-'),
(274,'Hana to Gaku','Hana to Gaku','Josei/BL','6 (finie)',NULL),
(275,'Hana to Gin','Hana to Gin','Yaoi','3 (en cours)',NULL),
(276,'Hana to Ikkun','Hana to Ikkun','Josei/BL','5 (finie)','-'),
(277,'Hana to Junketsu','Hana to Junketsu','Yaoi','5 (finie)',NULL),
(278,'Hana to Kuchizuke','Hana to Kuchizuke','Shojo','10 (en cours)','-'),
(279,'Hana to Usagi','Hana to Usagi','Josei/BL','3 (finie)','-'),
(280,'Hana wa Saku ka','Does the flower bloom?','Josei/BL','37 (finie)','-'),
(281,'Hanagara Tsumi','Hanagara Tsumi','Josei/BL','6 (finie)',NULL),
(282,'Hanakoi Tsurane','Hanakoi Tsurane','Shojo/BL','55 (en cours) 11,18, 21, 32,35','-'),
(283,'Hananoi-kun to koi no yamai','A tes côtés','Shojo','31 (en cours)','-'),
(284,'Hanyo no Yashahime','Yashahime: Princess Half-Demon','Shonen','-','2 saison (en cours)'),
(285,'Happy Birthday','Happy Birthday','Shojo/BL','11 (finie)',NULL),
(286,'Happy Mariage','Happy Mariage','Shojo/Josei','40 (fini)','-'),
(287,'Happy of the end','Happy of the end','Josei/BL','6 (finie)',NULL),
(288,'Happy Shitty Life','Happy Shitty Life','Yaoi','19 (finie)',NULL),
(289,'Haru ga Kita','Haru ga Kita','Josei/BL','6 (fine)','<3'),
(290,'Haru no Noroi','Haru no Noroi','Seinen','8 (finie)','-'),
(291,'Haruka Tooki Ie','Haruka Tooki Ie','Yaoi','6 (finie)',NULL),
(292,'Harukaze no Étranger','Harukaze no Étranger','Yaoi','vol 4 (fini)',NULL),
(293,'Hataraku saibou','Cells at Work/Les Brigades Immunitaires','Shonen','-','1 saison (en cours)'),
(294,'Hataraku Saibou BLACK','Cells at Work BLACK','Seinen','Vol 1','1 saison (en cours)'),
(295,'Hatsujou Relationship','Hatsujou Relationship','Yaoi','5 (finie)',NULL),
(296,'Hatsukoi no Atosaki','Hatsukoi no Atosaki','Josei/BL','4,5 (finie)','-'),
(297,'Hatsukoi no Tonari','Hatsukoi no Tonari','Josei/BL','6 (finie)','-'),
(298,'Hatsukoi note','Hatsukoi note','Yaoi','4 (finie)',NULL),
(299,'Hatsukoi note','Hatsukoi note','Yaoi','5 (finie)',NULL),
(300,'Hatsukoi Wa Gunjou Ni Tokeru','The First Love Melt in Ultramarine','Josei/BL','5 (finie)','-'),
(301,'Hatsunetsu Libido','Hatsunetsu Libido','Josei','8 (finie?)','-'),
(302,'Haunted by Desire','Haunted by Desire','Yaoi/Webtoon','85 (finie)',NULL),
(303,'Hauru no ugoku shiro','Le château ambulant','Film','-','film (fini)'),
(304,'Hearty','Hearty','Shojo/BL','6 (finie)','-'),
(305,'Heat and Run','Heat and Run','Yaoi/Webtoon','103 (finie)',NULL),
(306,'Hebikuidori','Hebikuidori','Josei/BL','4 (en cours?)','-'),
(307,'Heisei tanuki gassen ponpoko','Pompoko','Film','-','film (fini)'),
(308,'Hell & High Water','Hell & High Water','Yaoi/Webtoon','28 (finie)',NULL),
(309,'Hello','Hello','BL','5 (finie)',NULL),
(310,'Hello Morning Star','Hello Morning Star','Josei/BL','6 (finie)','-'),
(311,'Hi Manyuaru Ren Ai','Hi Manyuaru Ren Ai','Yaoi','1 (finie)',NULL),
(312,'Hi no Ataranai Basho','Hi no Ataranai Basho','Josei/BL','12 (finie)','-'),
(313,'Hidamari ga Kikoeru - Limit','I hear the Sunspot - Limit','Shojo/BL','29 (finie)','-'),
(314,'Hige Wo Soru. Soshite Joshikosei Wo Hirou.','I Shaved. Then I Brought a High School Girl Home.','Seinen','-','1 saison (en cours)'),
(315,'Hikaru ga Shinda Natsu','Hikaru ga Shinda Natsu','Shonen/BL/WTF','7 (en cours)',NULL),
(316,'Hime Muko','Hime Muko','Josei/BL','6 (finie)',NULL),
(317,'Himitsu no Asa ni wa Kiss no Ame','Himitsu no Asa ni wa Kiss no Ame','Yaoi','5 (en cours)',NULL),
(318,'Himitsu wa Kiss de Abakareru','himitsu wa kiss de abakareru','Yaoi','30 (finie)',NULL),
(319,'Himoxile','Himoxile','Seinen','1 one shot','-'),
(320,'Hinadori wa Shiokaze ni Madoromu','Hinadori wa Shiokaze ni Madoromu','Josei/BL','7 (finie)',NULL),
(321,'Hinekure Sakura ni Koi ga Saku','Hinekure Sakura ni Koi ga Saku','Josei/BL','4 (finie)',NULL),
(322,'Hirano to Kagiura','Hirano to Kagiura','Shojo/BL','15 (en cours)',NULL),
(323,'Hirunaka no Ryūsei','Daytime Shooting Star','Shojo','78 ( finie)','-'),
(324,'Hishakaishindo','Depth of Field','Josei/BL','9,5 (finie)','-'),
(325,'Hitori de Yoru wa Koe Rarenai','Hitori de Yoru wa Koe Rarenai','Yaoi','2 (en cours)',NULL),
(326,'Hitori to Hitori no 3650nichi','Hitori to Hitori no 3650nichi','Josei/BL','4 (finie)','-'),
(327,'Hitorijime - Choukyou Ganbou','Teach me love','Josei','17 (en cours)','-'),
(328,'Hitorijime My Hero','Hitorijime My Hero','Shonen ai','64 Vol 12 (en cours)','1 saison (finie)'),
(329,'Hitotsu Yane No Shita de... Kiraina Aitsu no Amai Yuuwaku','Hitotsu Yane No Shita de... Kiraina Aitsu no Amai Yuuwaku','Shojo','15 (finie)','-'),
(330,'Hitsuji no Kawa wo Kita Kemono','Hitsuji no Kawa wo Kita Kemono','Yaoi','8 (finie)',NULL),
(331,'Hōhokekyo tonari no Yamada-kun','Mes voisins les Yamada','Film','-','film (fini)'),
(332,'Honey × Honey Drops','Honey × Honey','Shojo','20 (fini)','-'),
(333,'Honnō Switch','Switch me on','Josei','27 Vol 11 (en cours)','-'),
(334,'Hori-san to Miyamura-kun','Horimiya','Shojo','125 (finie)','1 saison (finie)'),
(335,'Hosaka-san to Miyoshi-kun','Hosaka-san to Miyoshi-kun','Shojo/BL','2 (en cours)','-'),
(336,'Hoshi dake ga Shitteru','Hoshi dake ga Shitteru','Shojo/BL','7 (finie)','-'),
(337,'Hotaru no haka','Le Tombeau des Lucioles','Film','-','Film (finie)'),
(338,'Hotaru wa Ashita Shinu','Hotaru wa Ashita Shinu','Yaoi','6 (finie)',NULL),
(339,'Houkago no etude','Houkago no etude','Yaoi','6 (en cours VOl 2)',NULL),
(340,'Housekisho Richard-shi no Nazo Kantei','The Case Files of Jeweler Richard','Shojo','-','1 saison (finie)'),
(341,'How to snag an alpha','How to snag an alpha','Yaoi/Webtoon','103 (finie)',NULL),
(342,'Hukabato, shinigami katarite syuucyaku','Hukabato, shinigami katarite syuucyaku','Yaoi','2 (en cours)',NULL),
(343,'Hunter X Hunter','Hunter X Hunter','Shonen','-','3 saisons (en cours)'),
(344,'Hydrangea Cage','Hydrangea Cage','Yaoi','5 (finie)',NULL),
(345,'Hyperventilation','Hyperventilation','Yaoi/Webtoon','4 (finie)',NULL),
(346,'I Seriously Can''t Believe You..','I Seriously Can''t Believe You..','Yaoi','5 (finie)',NULL),
(347,'Ibara no Naka no Hana','Ibara no Naka no Hana','Josei/BL','8 (finie)',NULL),
(348,'Ibitsu na Koi no Seesaw Game','Ibitsu na Koi no Seesaw Game','Josei/BL','5 (en cours)','-'),
(349,'Ichijou Karen wa Yuuwakusuru','Ichijou Karen wa Yuuwakusuru','Shojo','6 (finie)','-'),
(350,'Ichika, Bachika','Ichika, Bachika','Josei/BL','5 finie)',NULL),
(351,'Iesu ka Nō ka Hanbun ka','Yes, No, Maybe half','Shojo/BL','-','Film OAV'),
(352,'Iji-ranaide, Nagatoro-san','Don''t Mess with Me, Nagatoro','Shonen','90 (en cours)',NULL),
(353,'Ikebukuro West Gate Park','Ikebukuro West Gate Park','Shonen','-','1 saison (finir)'),
(354,'Ikemen no Senpai ga Jitsu wa Doutei de Junjou Deshita','Ikemen no Senpai ga Jitsu wa Doutei de Junjou Deshita','Yaoi','6 (finie?)',NULL),
(355,'Ikenai Koto Shiyo?','Ca reste ente nous','Shojo','19 (finie)','-'),
(356,'Iki Dekinai no wa Kimi no Sei','Iki Dekinai no wa Kimi no Sei','Yaoi','13 (en cours)',NULL),
(357,'Ikotsu no Tabiji','Ikotsu no Tabiji','Josei/BL','6 (en cours)','-'),
(358,'In the cage','In the cage','Yaoi','6 (finie)',NULL),
(359,'In These Words','In These Words','Yaoi','(4 tomes)',NULL),
(360,'Inazuma to Romance','Inazuma to Romance','Shojo','13 (en cours)','-'),
(361,'Incidentally Living Together','Incidentally Living Together','Yaoi/Webtoon','46 (fine)',NULL),
(362,'Indigo no Kibun','Indigo no Kibun','Josei/BL','6 (finie)',NULL),
(363,'Intense','Intense','Yaoi/Webtoon','28 (finie)',NULL),
(364,'Inuyasha','Inuyasha','Shonen','-','7 saisons (finie)'),
(365,'Irony Dress ni Sayonara','Irony Dress ni Sayonara','Shojo/BL','5 (finie)','-'),
(366,'Irozuku sekai','IRODUKU : Le Monde en couleur','Seinen','-','1 saison (finie)'),
(367,'Itadakimasu, Gochisousama','Itadakimasu, Gochisousama','Josei/BL','5 (finie)','-'),
(368,'Itooshiki Hibi','Itooshiki Hibi','Yaoi','5 (finie)',NULL),
(369,'Itoshiki Ningyo','Itoshiki Ningyo','Yaoi','6 (finie)',NULL),
(370,'Itsuka Koi ni Naru Made','Let''s be a together','Josei/BL','10 (finie)','-'),
(371,'IWGP','IWGP','Shonen','-','1 saison (en cours)'),
(372,'Jackass!','Jackass!','Shojo/BL','6 (finie)','-'),
(373,'Jaku-Chara Tomozaki-kun','Bottom-tier Character Tomozaki','Shonen','-','4 (en cours)'),
(374,'Jealousy','Jealousy','Josei/BL','(finie)','-'),
(375,'Jimihen!! Jimiko wo Kaechau Jun Isei Kouyuu','Simple Yet Sexy','Josei','27 (en cours)','-'),
(376,'Jinx','Jinx','Yaoi/Webtoon','7 (en cours)',NULL),
(377,'JoJo no Kimyou na Bouken','Jojo’s Bizarre Adventure','Shonen','-','4 Saisons (en cours?)'),
(378,'Joou to Shitateya','Joou to Shitateya','Josei/BL','6 (finie)','-'),
(379,'Joukakei Kareshi','Joukakei Kareshi','Yaoi','7 (finie)',NULL),
(380,'Judge','Judge','Seinen','32 (finie)',NULL),
(381,'Jujutsu Kaisen','Jujutsu Kaisen','Shonen','178 (en cours)','1 saison (finie)'),
(382,'Junji Itô Collection','Itou Junji Jisen Kessakushuu','Seinen','-','1 saison'),
(383,'Junjo Romantica','Junjo Romantica','Shojo/BL','100.64 (en cours)','3 saison (finie)'),
(384,'Junjou Shounen','Junjou Shounen','Yaoi','6 (finie)',NULL),
(385,'Kaado Kyaputaa Sakura','Card Captor Sakura','Shojo','-','1 saison (regardé jeune)'),
(386,'Kachou Fuugetsu','Kachou Fuugetsu','Josei/BL','74 (en cours)',NULL),
(387,'Kagefumi no koi','Kagefumi no koi','Yaoi','2 (finie?)',NULL),
(388,'Kageri ni Komorebi, Sore kara Midori','Kageri ni Komorebi, Sore kara Midori','Shojo/BL','6 (finie)',NULL),
(389,'Kaguya Sama : Love is War','Kaguya Sama : Love is War','Shojo','163 (en cours)','2 saisons (en cours)'),
(390,'Kaguya-hime no monogatari','Le conte de la princesse Kaguya','Film','-','film (fini)'),
(391,'Kaichou wa Maid sama!','Kaichou wa Maid sama!','Shojo','-','1 saison (finie)'),
(392,'Kaijuu','Kaijuu','Josei/BL','6 (finie)',NULL),
(393,'Kainarasu Hazuga Aegasarete Komattemasu','Kainarasu Hazuga Aegasarete Komattemasu','Josei','6 (fini)','-'),
(394,'Kakushigoto','Kakushigoto','Seinen','-','1 saison (finie)'),
(395,'Kami-sama wa Chotto dake Ijiwaru','Kami-sama wa Chotto dake Ijiwaru','Josei/BL','5 (finie)',NULL),
(396,'Kamisama Hajimemashita','Divine Nanami','Shojo','Finie','2 saisons + OAV''s (finie)'),
(397,'Kamisama no Uroko','God''s Scales','Josei/BL','10 (finie)','-'),
(398,'Kamisamananka shinjinai bokua no Eden','Kamisamananka shinjinai bokua no Eden','Yaoi','(en cours) 1 tome',NULL),
(399,'Kanawanu Koi no Musubikata','Comment defier le destin','Josei/BL','6 (finie)',NULL),
(400,'Kanojo, Okarishimasu','Rent a girlfriend','Shonen','188 (en cours)','1 saison ( 2 saison 2021)'),
(401,'Kanon','Kanon','Shojo','-','1 saison (pas accroché)'),
(402,'Kanshaku Dama no Love Song','Kanshaku Dama no Love Song','Yaoi','6 ( finie)',NULL),
(403,'Kare no Shousou to Koi ni Tsuite','Kare no Shousou to Koi ni Tsuite','Josei/BL','14 (finie)','-'),
(404,'Karigurashi no Arietti','Arrietty, le petit monde des chapardeurs','Film','-','film (fini)'),
(405,'Kashikomarimashita, Destiny','Kashikomarimashita, Destiny','Josei/BL','12 (finie)',NULL),
(406,'Katsuyoku Scandal','Katsuyoku Scandal','Yaoi','6 (finie)',NULL),
(407,'Kaze tachinu','Le vente se lève','Film','-','film (fini)'),
(408,'Kedamono Arashi','Kedamono Arashi','Yaoi','5 (finie)',NULL),
(409,'Kedamono Arashi - Kiss Me Baby!','Kedamono Arashi - Kiss Me Baby!','Yaoi','4 (finie)',NULL),
(410,'Kedamono Arashi - Touch Me Baby!','Kedamono Arashi - Touch Me Baby!','Yaoi','5 (finie)',NULL),
(411,'Kedamono Arashi -Hold Me Baby!','Kedamono Arashi -Hold Me Baby!','Yaoi','5 (finie)',NULL),
(412,'Kedamono Arashi: Hug Me Baby!','Kedamono Arashi: Hug Me Baby!','Yaoi','5 (finie)',NULL),
(413,'Keeper of the pearl','Keeper of the pearl','Yaoi/Webtoon','49 (finie)',NULL),
(414,'Keisenjou no Cantata','Keisenjou no Cantata','Josei/BL','6 (finie)',NULL),
(415,'Kekkon Shite Kudasai!','Kekkon Shite Kudasai!','Yaoi','6 (finie)',NULL),
(416,'Kekkon Suru Kamoshirenai Otoko','Kekkon Suru Kamoshirenai Otoko','Josei/BL','5 (en cours)',NULL),
(417,'Kemono Asobi','Kemono Asobi','Josei/BL','5 (finie)',NULL),
(418,'Kenka banchou otome','Girl Beats Boys','Shojo','-','1 saison'),
(419,'Kids on the Slope','Sakamichi no Apollon','Josei','-','1 saison (finie)'),
(420,'Killing Stalking','Killing Stalking','Seinen','67 (finie)','-'),
(421,'Kimagure na Jaguar','Kimagure na Jaguar','Yaoi','24 (finie)',NULL),
(422,'Kimetsu no Yaiba','Demon Slayer','Shonen','-','1 Saison  + OAV (octobre)'),
(423,'Kimi ga Kagi woAkerumade','Kimi ga Kagi woAkerumade','Josei/BL','5 (finie)','-'),
(424,'Kimi ni Aisarete Itakatta','Brisée par ton amour','Seinen','21 (en cours)','-'),
(425,'Kimi ni Ienai Koto ga Aru','Kimi ni Ienai Koto ga Aru','Shojo/BL','6 (finie)','-'),
(426,'Kimi ni Todoke','Sawako','Shojo','-','2 saisons (finie)'),
(427,'Kimi ni wa Fureru to Naru Toko ga Atte','Kimi ni wa Fureru to Naru Toko ga Atte','Yaoi','5 ( finie)',NULL),
(428,'Kimi no na wa','Your Name','Film','-','film (fini)'),
(429,'Kimi no Suizō wo Tabetai','Je veux manger ton pancréas','Seinen','10 (finie)','-'),
(430,'Kimi no Wasurekata wo Oshiete','I''m still thinking about you','Seinen','5 (arretée)','-'),
(431,'Kimi to Unmei ni Tsuite no Hanashi ga Shitai','Kimi to Unmei ni Tsuite no Hanashi ga Shitai','Yaoi','5 (finie)',NULL),
(432,'Kimi wa Jun''ai ni Fusawashii','Kimi wa Jun''ai ni Fusawashii','Yaoi','6 (finie)',NULL),
(433,'Kimi wa pet','Kimi wa pet','Josei','82 (fini)','-'),
(434,'King''s Maker Triple Crown','King''s Maker Triple Crown','Yaoi/Webtoon','98 (finie)',NULL),
(435,'Kiraide Isasete','Kiraide Isasete','Josei/BL','Vol 4 (chp4)','-'),
(436,'Kiryuu-sensei wa Renai ga Wakaranai','Aromantic (love) story','Josei','12 (en cours)',NULL),
(437,'Kisarazu kun no XX ga mitai','Kisarazu kun no XX ga mitai','Josei','19 (en cours)','-'),
(438,'Kiseijuu: Sei no Kakuritsu','Parasite','Seinen','-','1 saison (finie)'),
(439,'Kishukusha no Kuroneko wa Yoru wo Shiranai','Kishukusha no Kuroneko wa Yoru wo Shiranai','Yaoi','2 (en cours)',NULL),
(440,'Kiss me Liar','Kiss me Liar','Yaoi/Webtoon','48+sides (finie)',NULL),
(441,'Kiss wa Tsugai ni Hizamazuku','Kiss wa Tsugai ni Hizamazuku','Yaoi','7 (en cours)',NULL),
(442,'Kitto Oujisama ga Nante','Kitto Oujisama ga Nante','Josei/BL','5 (finie)','-'),
(443,'Kitto, Shiawase na Ketsumatsu','Kitto, Shiawase na Ketsumatsu','Josei/BL','7 (finie)',NULL),
(444,'Kobi no Isu','Kobi no Isu','Josei/BL','3 (finie)','-'),
(445,'Kocchi Muite','Kocchi Muite','Yaoi','5 (finie)',NULL),
(446,'Koi da Ai da wa Sateoite','Koi da Ai da wa Sateoite','Josei/BL','6 (finie)','-'),
(447,'Koi Ga Michitara','Koi Ga Michitara','Josei/BL','6 (finie)',NULL),
(448,'Koi ga Ochitara','Koi ga Ochitara','Josei/BL','5 (finie)',NULL),
(449,'Koi Kirari, Kage Sururi','Koi Kirari, Kage Sururi','Josei/BL','6 (finie)','-'),
(450,'Koi Monogatari','Koi Monogatari','Shonen ai','24 (en cours)',NULL),
(451,'Koi nanka Shitakunai','Koi nanka Shitakunai','Josei/BL','8 (finie)','-'),
(452,'Koi to Producer : Evol x Love','Koi to Producer: EVOL×LOVE','Shojo','-','1 saison (en cours?)'),
(453,'Koi to wa Baka de Aru Koto da','Koi to wa Baka de Aru Koto da','Josei/BL','6 (finie)','-'),
(454,'Koi to Yobu ni wa Kimochi Warui','Koikimo','Josei','26 (en cours)','1 saison (finie)'),
(455,'Koi wa Ameagari no You ni','After the rain','Seinen','-','1 saison (finie)'),
(456,'Koi wa Tsuzuku yo Dokomade mo','Check me up!','Josei','35 (fini)','-'),
(457,'Koi wo suru ni wa toumei sugiru','Koi wo suru ni wa toumei sugiru','Josei/BL','3 (en cours)',NULL),
(458,'Koi wo Suru Tsumori wa Nakatta','I Didn''t Mean to Fall in Love','Josei/BL','5 (finie)','-'),
(459,'Koji Koi','Koji Koi','Shojo','9 (en cours)','-'),
(460,'Kokkoku','Kokkoku','Seinen','-','1 saison (à finir)'),
(461,'Kokoro o Korosu Houhou','Kokoro o Korosu Houhou','Josei/BL','17 (finie)',NULL),
(462,'Kokuriko zaka kara','La colline aux coquelicots','Film','-','film (fini)'),
(463,'Komi-san wa Komyushou Desu','Komi-san wa Komyushou Desu','Shonen','-','1 (saison)'),
(464,'Konin Todoke ni Han wo Oshita dake desu ga','Konin Todoke ni Han wo Oshita dake desu ga','Josei','4 (en cours)','-'),
(465,'Kono Inu wa Mada Amai Doku wo Shiranai','Kono Inu wa Mada Amai Doku wo Shiranai','Josei/BL','4 (finie)','-'),
(466,'Kono koi ni Mirai wa nai','Celle que je suis','Josei','12,5 (finie)','-'),
(467,'Kono Ore ga Omae nanka Suki na Wakenai','Kono Ore ga Omae nanka Suki na Wakenai','Shojo/BL','5 (finie)','-'),
(468,'Kono Oto Tomare !','Kono Oto Tomare !','Shojo','115 (en cours)','2 saisons (en cours?)'),
(469,'Kono Senaka ni Tsume wo Tatete','Kono Senaka ni Tsume wo Tatete','Josei/BL','6 (finie)','-'),
(470,'Kono Te wo Hanasanai de','Kono Te wo Hanasanai de','Yaoi','5 (finie)',NULL),
(471,'Konya Kimi to Nemuritai','Konya Kimi to Nemuritai','Josei/BL','5 (finie)','-'),
(472,'Koori Zokusei Danshi to Cool na Douryo Joshi','Ice Guy and the Cool Female Colleague','Seinen','36 (en cours)','-'),
(473,'Korogaru Onna to Koi no Numa','Korogaru Onna to Koi no Numa','Shojo','7 (en cours)','-'),
(474,'Koroshi Ai','Koroshi Ai','Seinen','57 (en cours) 70 raw','1 saison (en cours)'),
(475,'Koto no ha no niwa','The Garden of Words','Film','-','film (fini)'),
(476,'Kozure Omega to Boukun Yakuza','Kozure Omega to Boukun Yakuza','Yaoi','5 (en cours)',NULL),
(477,'Kumichou Musume to Sewagakari','Kumichou Musume to Sewagakari','Seinen','-','1 saison'),
(478,'Kuragehime','Princess Jellyfish','Josei','25 (en cours)','1 saison'),
(479,'Kurenai no buta','Porco Rosso','Film','-','film (fini)'),
(480,'Kureyon Shinchan','Crayon Shin-chan','Seinen','-','regardé jeune'),
(481,'Kuro ka, Shiro ka','Black and White','Yaoi','15 (en cours)',NULL),
(482,'Kurozuka','Kurozuka','Seinen','-','1 saison (Ep 4 à finir)'),
(483,'Kurui Naku no wa Boku no Ban','Kurui Naku no wa Boku no Ban','Josei/BL','14 (finie)',NULL),
(484,'Kuu Neru Futari Sumu Futari','Living, Eating and Sleeping Together','Seinen','Chapitre 7 (vol 2)','-'),
(485,'Kuzu no Honkai','Kuzu no Honkai / Scum''s wish','Seinen','-','1 saison (finie)'),
(486,'Kyokou Suiri','In Spectre','Shonen','-','1 saison (fini) 2 saison 2021'),
(487,'Kyoto Teramachi Sanjou no Holmes','Holmes of Kyoto','Seinen','-','1 saison (finie) LN'),
(488,'Kyuuketsuki ha shinzo no yume wo miru','Kyuuketsuki ha shinzo no yume wo miru','Yaoi','6 (finie)',NULL),
(489,'Kyuuketsuki Sugu Shinu - Vampire dies in no time','Kyuuketsuki Sugu Shinu - Vampire dies in no time','Shonen','-','10 (en cours)'),
(490,'Last Omegaverse','Last Omegaverse','Yaoi','6 (finie)',NULL),
(491,'Let''s be a family','Let''s be a family','Josei/BL','7 (finie)','-'),
(492,'Life Senjou no Bokura','Life Senjou no Bokura','Yaoi','5 (finie)',NULL),
(493,'Light of My Life','Light of My Life','Josei/BL','6 (finie)',NULL),
(494,'Like a Tidal Wave','Like a Tidal Wave','Yaoi/Webtoon','20 (finie)',NULL),
(495,'Limited Run','Limited Run','Yaoi/Webtoon','57 (en cours)',NULL),
(496,'Lion Gotoki no Kuni Kara','Lion Gotoki no Kuni Kara','Yaoi','1 tome (finie)',NULL),
(497,'Lionhearts','Lionhearts','Shojo/BL','6 (en cours)','-'),
(498,'Liquor & Cigarette','Liquor & Cigarette','Josei/BL','5 (finie)','-'),
(499,'Living Dead','Living Dead','Yaoi','2 (finie)',NULL),
(500,'Living no Matsunaga-san','Mon coloc'' d''enfer','Shojo','44 (fine)','-'),
(501,'Lone Wolf and Cub','Lone Wolf and Cub','Seinen','Vol 3',NULL),
(502,'Lonely to Organdy','Lonely to Organdy','Shojo/BL','5 (finie)','-'),
(503,'Lost in the cloud','Lost in the cloud','Yaoi/Webtoon','75 (en cours)',NULL),
(504,'Love Hina','Love Hina','Shonen','2 tomes (en cours)','-'),
(505,'Love is an illusion','Love is an illusion','Yaoi/Webtoon','99 (finie)',NULL),
(506,'Love Nest','Love Nest','Josei/BL','11 (finie)',NULL),
(507,'Love Nest 2nd','Love Nest 2nd','Josei/BL','14 (finie)','-'),
(508,'Love Shuttle','Love Shuttle','Yaoi/Webtoon','90 (finie)',NULL),
(509,'Love so pure','Love so pure','Yaoi/Webtoon','102 (en cours)',NULL),
(510,'Love Stage','Love Stage','Yaoi','33 (finie)','1 saison (finie)'),
(511,'Loved Circus','Loved Circus','Yaoi','6 (finie)',NULL),
(512,'Lovely Complex','Lovely Complex','Shojo','-','1 saison (finie)'),
(513,'Low Tide in Twilight','Low Tide in Twilight','Yaoi/Webtoon','61 (en cours)',NULL),
(514,'Loxe x Dilemma','Domestic na Kanojo','Shonen','276 (fini)','1 saison (?)'),
(515,'Made in Abyss','Made in Abyss','Seinen','-','1 saison (finie)'),
(516,'Made in Abyss : L''Aurore De L''Âme Des Profondeurs','Made in Abyss : L''Aurore De L''Âme Des Profondeurs','Film','-','Film OAV'),
(517,'MADK','MADK','Yaoi','Vol 2 (finie)',NULL),
(518,'Mahō Tsukai no Yome','The Ancient Magus Bride','Shonen','-','1 saison (finie))'),
(519,'Majo no takkyūbin','Kiki la petite sorcière','Film','-','film (fini)'),
(520,'Majo to Neko','Majo to Neko','Yaoi','5 (finie)',NULL),
(521,'Majo-senpai Nippou','Majo-senpai Nippou','Josei','36 (en cours)','-'),
(522,'Make It Only Love','Make It Only Love','Shojo/BL','5 (finie)','-'),
(523,'Make me bark','Make me bark','Yaoi/Webtoon','35 (finie)',NULL),
(524,'Makkurayami De Kimi To','Makkurayami De Kimi To','BL','6 ( finie)','-'),
(525,'Makotoshiyaka ni Mau Hana wa','Makotoshiyaka ni Mau Hana wa','Yaoi','6 (finie)','-'),
(526,'Manatsu no Siren','Manatsu no Siren','Yaoi','4 (en cours)',NULL),
(527,'Mania','Mania','Yaoi/Webtoon','63 (finie)',NULL),
(528,'Maou Gakuin no Futekigousha','The misfit of the demon king Academy','Shonen','-','1 saison (2 saison?) Light Novel'),
(529,'Mashiro no Oto','Those Snow White Notes','Shonen','-','1 saison (en cours)'),
(530,'Mask Danshi wa Koishitakunai no ni','Mask Danshi wa Koishitakunai no ni','Josei/BL','21 (en cours)','-'),
(531,'Megumi and Tsugumi','Megumi and Tsugumi','Josei/BL','Vol 4 (chp2)','-'),
(532,'Meiji Juuzoku Tungsten','Meiji Juuzoku Tungsten','Josei/BL','4 (en cours)',NULL),
(533,'Melon no Aji','The Flavor of Melon','Josei/BL','5 ( finie)',NULL),
(534,'Melt at night','Melt at night','Josei/BL','5 (finie)','-'),
(535,'Memento Scarlet','Memento Scarlet','Yaoi','6 (finie)',NULL),
(536,'Midnight Rain','Midnight Rain','Yaoi','7 ( finie)',NULL),
(537,'Mieruko chan','Mieruko chan','Seinen','-','1 saison'),
(538,'Mihanada Pectolite','Mihanada Pectolite','Shojo/BL','5 (finie)',NULL),
(539,'Mijukuna Papa wa Share House de Koi wo Shiru','Mijukuna Papa wa Share House de Koi wo Shiru','Josei/BL','5 (finie)','-'),
(540,'Mimi o sumaseba','Si tu tends l''oreille','Film','-','film (fini)'),
(541,'Minori no Te','Minori no Te','Josei/BL','6 (finie)','-'),
(542,'Miraiken de Ai o Tsumugeba','Weaving Love in the Future','Josei/BL','Finie','-'),
(543,'Misaki-kun no Bukiyou na Dekinai','Misaki-kun no Bukiyou na Dekinai','Shojo','5 (en cours)','-'),
(544,'Mob Psycho 100','Mob Psycho 100','Shonen','-','1 saison (à finir)'),
(545,'Mobius Strip','Mobius Strip','Josei','5,5 (fini)','-'),
(546,'Mobuko no Koi','Mobuko no Koi','Shojo','57 (en cours)',NULL),
(547,'Mods','Mods','Josei/BL','5 (finie)','-'),
(548,'Moekare wa Orange-iro','My boyfriend in orange','Shojo','44 (en cours)','-'),
(549,'Mofuku No Hanayome','Mofuku No Hanayome','Josei/BL','5 (finie)','-'),
(550,'Momo to Manji','Momo to Manji','Josei/BL','3 (en cours)','-'),
(551,'Monokuro Limit','Monokuro Limit','Shojo/BL','5 (finie)','-'),
(552,'Mononoke hime','Princesse Mononoké','Film','-','film (fini)'),
(553,'Monster','Monster','Seinen','-','1 saison (finie)'),
(554,'Moon and Sun','Moon and Sun','Josei/BL','9 (finie)',NULL),
(555,'Moshi Ero  - Eroman - Kami to Pen to Sex to!!','Moshi Ero - Eroman - Kami to Pen to Sex to!!','Josei/BL','5 (finie)','-'),
(556,'Mou ichido','Mou ichido','Josei','9 (fini)','-'),
(557,'Mr. 100% Perfect','Mr. 100% Perfect','Yaoi/Webtoon','92 ( en cours)',NULL),
(558,'Mugi-kun Ni Koi Wo Shite Wa Ikenai','Mugi-kun Ni Koi Wo Shite Wa Ikenai','Shojo/Josei','9 (en cours)','-'),
(559,'Mujaki na Wanko to Nekokaburi','Mujaki na Wanko to Nekokaburi','Josei/BL','5 (finie)','-'),
(560,'Murikon','Muri Marriage','Josei/BL','6 (finie)',NULL),
(561,'My Home Your Oneroom','My Home Your Oneroom','Shojo/BL','5 (finie)',NULL),
(562,'My little Inferno','My little Inferno','Shojo/BL','10 (finie)',NULL),
(563,'Nakanai Hibari','Nakanai Hibari','Shojo/BL','5 (finie)',NULL),
(564,'Namaiki Kareshi','Namaiki Kareshi','Yaoi','6 (finie)',NULL),
(565,'Namida Kareru na','Namida Kareru na','Josei/BL','6 (finie)',NULL),
(566,'Namida no Priceless','Namida no Priceless','Yaoi','6 (en cours)',NULL),
(567,'Nana','Nana','Shojo/Josei','84 (en cours?)','1 saison'),
(568,'Nanatsu no Taizai','Seven deadly sins','Shonen','-','4 saisons (en cours)'),
(569,'Naruto','Naruto','Shonen','-','5 saisons (finie)'),
(570,'Naruto Shippuden','Naruto Shippuden','Shonen','-','21 saisons (à finir)'),
(571,'Naruto the Last','Naruto the Last','Film','-','Film OAV'),
(572,'Natsuyuki Rendez-vous','Natsuyuki Rendez-vous','Josei','-','1 saison (finie)'),
(573,'Neko no ongaeshi','Le Royaume des Chats','Film','-','film (fini)'),
(574,'Neko x Neko','Neko x Neko','Yaoi','13 (finie) 3 volumes',NULL),
(575,'Nen Nen Sai Sai','Nen Nen Sai Sai','Josei/BL','5 (finie)','-'),
(576,'Neon Genesis Evangelion Gekijouban : The End of Evangelion : Air/Magokoro wo, Kimi ni','The End of Evangelion','Film','-','Film OAV'),
(577,'Neon Sign Amber','Neon Sign Amber','Josei/BL','5 (finie)',NULL),
(578,'Net-jû no Susume','Recovery of an MMO Junkie','Seinen','-','1 saison (finie)'),
(579,'Netsuai Nante Ariemasen!','Netsuai Nante Ariemasen!','Yaoi','6 (finie)',NULL),
(580,'NHK ni youkoso!','Bienvenue dans la NHK','Seinen','-','1 saison (finie)'),
(581,'Ni no Kuni','Ni no Kuni','Film','-','film (fini)'),
(582,'Nigeru wa Haji da ga Yaku ni Tatsu','The Full-Time Wife Escapiest','Josei','44 (finie)','-'),
(583,'NightS','NightS','Josei/BL','-','5 (finie)'),
(584,'Nights Before Night','Nights Before Night','Josei/BL','8 (finie)','-'),
(585,'Nii-chan','Nii-chan','Seinen','6 (fine)','-'),
(586,'Nijiiro Days','Rainbow Days','Shojo','59 (fini)','1 saison (finie)'),
(587,'Nikushoku Danshi to Soshoku Danshi','Nikushoku Danshi to Soshoku Danshi','Shojo/BL','6 (finie)',NULL),
(588,'Nirameba Koi','Nirameba Koi','Yaoi','11 (finie)',NULL),
(589,'Nobunaga Kyousoukyoku','Nobunaga  Concerto','Shonen','-','1 saison (à finir)'),
(590,'Nodame Cantabile','Nodame Cantabile','Seinen/Josei','-','1 saison (en cours)'),
(591,'Nomi x Shiba','Nomi x Shiba','Shojo/BL','5 (en cours)',NULL),
(592,'Noragami','Noragami','Shonen','96.2 (en cours)','2 saisons (finie?)'),
(593,'Noraneko to yubikiri','Noraneko to yubikiri','Shojo/BL','6 (finie)',NULL),
(594,'Noru ka Soru ka','Noru ka Soru ka','Josei/BL','5 (finie)',NULL),
(595,'Nure Nezumi-tachi no Koi','Nure Nezumi-tachi no Koi','Yaoi','4 (finie)',NULL),
(596,'O.B Occupation to Beloved','O.B Occupation to Beloved','Shojo/BL','7 (finie)','7'),
(597,'Oda Nobunaga','L''homme qui tua Oda Nobunaga','Seinen','3 vol mais bof','-'),
(598,'Odoru Ahou to Kusare Gedou','Odoru Ahou to Kusare Gedou','Yaoi','Nouveauté (chp2)',NULL),
(599,'Oita ga Sugiru wa Koneko-chan','Oita ga Sugiru wa Koneko-chan','Josei/BL','5 (finie)','-'),
(600,'Ojou to Banken-kun','Ojou to Banken-kun','Shojo','33 (en cours)','-'),
(601,'Ojou-sama ga Mamorasete Kurenai','Ojou-sama ga Mamorasete Kurenai','Josei','20 (en cours - scan arrété?)','-'),
(602,'Ōkami kodomo no Ame to Yuki','Les enfants Loups','Film','-','film (fini)'),
(603,'Okusama wa Alpha','Okusama wa Alpha','Yaoi','7 (finie)',NULL),
(604,'Old-fashioned Cupcake','Old-fashioned Cupcake','Josei/BL','Vol2 chap 5 (en cours)','-'),
(605,'Omae no Koi wa Ore no Mono','Omae no Koi wa Ore no Mono','Yaoi','5 (finie)',NULL),
(606,'Omaede Dame Nara Moudameda','Omaede Dame Nara Moudameda','Josei/BL','7 (finie)',NULL),
(607,'Omega Allergy','Omega Allergy','Yaoi','6 (finie)',NULL),
(608,'Omega Complex','Omega Complex','Yaoi/Webtoon','41 (finie)',NULL),
(609,'Omoide no Mānī','Souvenirs de Marnie','Film','-','film (fini)'),
(610,'Omoide poro poro','Souvenirs goutte à goutte','Film','-','film (fini)'),
(611,'On Doorstep','On Doorstep','Yaoi','5 (finie)',NULL),
(612,'On or Off','On or Off','Yaoi/Webtoon','91 (finie)',NULL),
(613,'On This Auspicious Day','On This Auspicious Day','Josei/BL','6 (finie)',NULL),
(614,'One Piece','One Piece','Shonen','1002 (en cours)','20 saisons (en cours)'),
(615,'One Piece Gold','One Piece Gold','Film','-','Film OAV'),
(616,'One Piece Stampede','One Piece Stampede','Film','-','Film OAV'),
(617,'One punch man','One punch man','Shonen','-','2 saisons'),
(618,'Oni to Tengoku','Oni to Tengoku','Yaoi','13 (finie)',NULL),
(619,'Oni to Tengoku Sai','Oni to Tengoku Sai','Yaoi','5 ( finie)',NULL),
(620,'Onihei Hankachou','Onihei','Seinen','-','1 saison (en cours)'),
(621,'Only You, Only','Only You, Only','Josei/BL','7 (finie)',NULL),
(622,'Onna no Sono no Hoshi','Onna no Sono no Hoshi','Seinen','3 (en cours)','-'),
(623,'Ookami Shoujo to Kuro Ouji','Wolf Girl & Black Prince','Shojo','-','1 saison (finie)'),
(624,'Ookami wa Hana No Kaori','Ookami wa Hana No Kaori','Shojo','10 (en cours)','-'),
(625,'Ooku','Le Pavillon des Hommes','Josei','4 (en cours)','-'),
(626,'Open Board','Open Board','Yaoi/Webtoon','25 (finie)',NULL),
(627,'Orange','Orange','Shojo','22 (fini)','-'),
(628,'Ore no Oniku-chan','Ore no Oniku-chan','Josei/BL','5 (finie)',NULL),
(629,'Ore to Joushi no Kakushigoto','Ore to Joushi no Kakushigoto','Josei/BL','5 (finie)',NULL),
(630,'Ore wo Mite','Ore wo Mite','Josei/BL','7 (finie)',NULL),
(631,'Oretachi Bijinesu Tsugai Yattemasu!','Oretachi Bijinesu Tsugai Yattemasu!','Yaoi','5 (en cours)',NULL),
(632,'Osake wa Fuufu ni Natte kara','Love is Like a Cocktail','Seinen','-','1 saison'),
(633,'Osananajimi (♂) to no Arekore','Osananajimi (♂) to no Arekore','Shojo/BL','6 (finie)','-'),
(634,'Osananajimi ja Gaman Dekinai','Osananajimi ja Gaman Dekinai','Shojo/BL','2 (en cours)','-'),
(635,'Otona Najimi','Otona Najimi','Shojo','12 (en cours)','-'),
(636,'Otona nya Koi no Shikata ga Wakaranee!','Adieu, la vie sans sexe','Josei','112 (en cours)','-'),
(637,'Otona wo Komaraserun Ja Arimasen!','Otona wo Komaraserun Ja Arimasen!','Josei/BL','2 (en cours)','-'),
(638,'Otouto no otto','Otouto no otto','Seinen','28 (finie)',NULL),
(639,'Ou-sama to Puppy Love','Ou-sama to Puppy Love','Yaoi','7 (finie)',NULL),
(640,'Ougo Mitsunaga wa Namagoroshi ga Tsurai','Ougo Mitsunaga wa Namagoroshi ga Tsurai','Shojo','8 (finie)','-'),
(641,'OUROBOROS','OUROBOROS','Yaoi/Webtoon','81 (finie)',NULL),
(642,'Outside Flower','Outside Flower','Shojo/BL','5 (finie)','-'),
(643,'Over Squall','Over Squall','Yaoi','7 (finie)',NULL),
(644,'Owaranai Fukou Ni Tsuite No Hanashi','Owaranai Fukou Ni Tsuite No Hanashi','Josei/BL','5 (finie)','-'),
(645,'Owner of the (Animal) Detective Agency','Owner of the (Animal) Detective Agency','Yaoi','7 (finie)',NULL),
(646,'Oyasuminasai no Ato wa','Oyasuminasai no Ato wa','Josei/BL','5 (finie)',NULL),
(647,'P to JK','My Boy in Blue','Shojo','62 (finie)','-'),
(648,'Page o Mekuru Sono Mae ni','Page o Mekuru Sono Mae ni','Yaoi','7 (en cours)',NULL),
(649,'Painter of the night','Painter of the night','Josei/BL','112 (en cours)','-'),
(650,'Papa x Papa - α To Ω De Sorezore Yattemasu','Papa x Papa - α To Ω De Sorezore Yattemasu','Yaoi','14 (finie) 15 new vol',NULL),
(651,'Paradigm Shift','Paradigm Shift','Josei/BL','5 (finie)',NULL),
(652,'Paradise kiss','Paradise Kiss','Shojo/Josei','-','1 saison (finie)'),
(653,'Paradise View','Paradise View','Shojo/BL','9 (finie)','-'),
(654,'Paripi Koumei','Paripi Koumei','Shonen','1 saison',NULL),
(655,'Payback','Payback','Yaoi/Webtoon','55 (en cours)',NULL),
(656,'Peace Maker Kurogane','Peace Maker Kurogane','Shonen','-','25 (finie)'),
(657,'Pearl Boy','Pearl Boy','Yaoi/Webtoon','62 (en cours)',NULL),
(658,'Pendulum: Kemonobito Omegaverse','Pendulum: Kemonobito Omegaverse','Yaoi','6 (finie)',NULL),
(659,'Perfect Blue','Perfect Blue','Seinen','-','FIlm'),
(660,'Perfect Buddy','Perfect Buddy','Yaoi/Webtoon','10 ( en cours)',NULL),
(661,'Perfect crime','Pièges charnels','Josei','13 (bof)',NULL),
(662,'Perfect Propose','Perfect Propose','Josei/BL','6 (finie)','-'),
(663,'Perfect World','Perfect World','Shojo/Josei','59 (finie)','-'),
(664,'Pet','Pet','Seinen','-','1 saison (finie)'),
(665,'Pet Shop Boys','Pet Shop Boys','Seinen','15 (en cours)','-'),
(666,'Petit Mignon','Petit Mignon','Shojo/BL','13 (en cours)',NULL),
(667,'Pink Heart-Jam','Pink Heart-Jam','Josei/BL','10 (en cours)','-'),
(668,'Pink to Mameshiba','Pink to Mameshiba','Josei/BL','6 (finie)','-'),
(669,'Platinum blood','Platinum blood','Yaoi','4 (en cours)',NULL),
(670,'Platinum End','Platinum End','Shonen','-','5 (en cours)'),
(671,'Play after call','Play after call','Yaoi','1 tome (finie)',NULL),
(672,'Playtime with Hakdo','Playtime with Hakdo','Yaoi/Webtoon','49 (finie)',NULL),
(673,'Pokemon','Pokemon','Shonen','-','1 saison (regardé jeune)'),
(674,'Pornographer','Pornographer','Josei/BL','7 (finie)',NULL),
(675,'Principle','Principle','Josei/BL','6 (finie)',NULL),
(676,'Psycho-Pass','Psycho-Pass','Seinen','Saison 1',NULL),
(677,'QQ Sweeper','QQ sweeper','Shojo','15 (finie)','-'),
(678,'Queen''s quality','Queen''s quality','Shojo','65 (en cours) VOL 14','-'),
(679,'Rainy Days, Yesterday','Rainy Days, Yesterday','Yaoi','5 (finie)',NULL),
(680,'Raise wa Tanin ga li','An outsider is better in the afterlife','Seinen','28 .3 (en cours)','-'),
(681,'Rakka Ryuusui no Hoshi','Rakka Ryuusui no Hoshi','Josei/BL','5 (finie)','-'),
(682,'Ranma Nibun no Ichi','Ranma 1/2','Shonen','-','1 saison (regardé jeune)'),
(683,'Rational Perverted Romance','Rational Perverted Romance','Yaoi','5 (finie)',NULL),
(684,'Re:Birth','Re:Birth','Josei/BL','4 (finie)',NULL),
(685,'RE:Zero','RE:Zero','Seinen','-','2 saison (finie) Light Novel'),
(686,'Red Beryl ni Sayonara','Red Beryl ni Sayonara','Yaoi','14 ( finie)',NULL),
(687,'ReLIFE','ReLIFE','Seinen','-','1 saison + OAV final (finie)'),
(688,'Remnant: Kemonohito Omegaverse','Remnant: Kemonohito Omegaverse','Yaoi','25 (en cours)',NULL),
(689,'Renai Gokko Sayokyoku','Renai Gokko Sayokyoku','Shojo','18 (en cours)','-'),
(690,'Renai Metro','Renai Metro','Josei','10 (fini)','-'),
(691,'Renai Nante Itashimasen!','Renai Nante Itashimasen!','Yaoi','5 (finie)',NULL),
(692,'Renai Nante Yurushimasen!','Renai Nante Yurushimasen!','Josei/BL','6 (finie)','-'),
(693,'Renai-Rubi no Tadashii Furikata','Renai-Rubi no Tadashii Furikata','Josei/BL','6 (finie)','-'),
(694,'Renai-rubi no Tadashii Furikata','Renai-rubi no Tadashii Furikata','Josei/BL','7 (finie)','-'),
(695,'Reply','Reply','Yaoi','3 (finie)',NULL),
(696,'Restart wa Onaka wo Sukasete','Restart wa Onaka wo Sukasete','Shojo/BL','7 (finie)',NULL),
(697,'Restart wa Tadaima no Ato de','Restart wa Tadaima no Ato de','Shojo/BL','6 (finie)',NULL),
(698,'Retro BL','Retro BL','Josei/BL','8 (finie)','-'),
(699,'Reverse','Reverse','Josei/BL','4 (en cours)',NULL),
(700,'Revival Blue','Revival Blue','Josei/BL','12 (finie)','-'),
(701,'Rift','Rift','Josei/BL','5.5 (fine)','-'),
(702,'riht.','riht.','Shojo/BL','6 (finie)','-'),
(703,'Rikei ga Koi ni Ochita no de Shoumei Shite Mita.','Science fell in love, so I tried to prouve it','Shonen','-','1 saison (2 saison 2021?)'),
(704,'Riso no Otoko','Riso no Otoko','Josei','20 (en cours)','-'),
(705,'Ristorante Paradiso','Ristorante Paradiso','Seinen','-','1 saison (finie)'),
(706,'Rix Vanus','Rix Vanus','Yaoi/Webtoon','147 ( en cours)',NULL),
(707,'Romance and Jealousy','Romance and Jealousy','Josei/BL','5 (finie)',NULL),
(708,'Romance ni wa Hodo Tooi','Far from Romance','Josei/BL','5 (finie)',NULL),
(709,'Romantic Joutou','Romantic Joutou','Yaoi','6 (en cours)',NULL),
(710,'Romantic Lament','Romantic Lament','Josei/BL','5 (finie)',NULL),
(711,'Roses and Chamapgne','Roses and Chamapgne','Yaoi/Webtoon','51 (finie)',NULL),
(712,'Rumspringa no Joukei','Rumspringa no Joukei','Yaoi','6 (finie)','-'),
(713,'Rurouni Kenshin','Kenshin Le Vagabond','Shonen','255 + suite Arc Hokkaido chapt 37 - oct?','1 saison (finie)'),
(714,'Rurouni Kenshin : Meiji Kenkaku Romantan - Tsuioku Hen','Kenshin le Vagabond : Le chapitre de la mémoire','Film','-','Film OAV'),
(715,'Sabita Yoru Demo Koi Wa Sasayaku','Sabita Yoru Demo Koi Wa Sasayaku','Josei/BL','4 (en cours)','-'),
(716,'Saezuru Tori wa Habatakanai','Twittering Birds Never Fly : The Clouds Gather','Josei','48 (en cours) V7 prochian chap fin mai 24/','Film'),
(717,'Sakura-gari','Sakura-gari','Shojo/BL','9 (finie)','-'),
(718,'Samouraï shamploo','Samouraï shamploo','Seinen','-','1 saison (finie)'),
(719,'Samurai Omega to Akutoku Shachou','Samurai Omega to Akutoku Shachou','Yaoi','5 (finie)',NULL),
(720,'Sankaku Mado no Sotogawa wa Yoru','The Night Beyond the Tricornered Window','Mysterie','-','4 (en cours)'),
(721,'Sasaki to Miyano','Sasaki to Miyano','Shonen ai','44 (en cours)','-'),
(722,'Sayonara Alpha','Sayonara Alpha','Josei/BL','5 (finie)',NULL),
(723,'Sayonara Game','Sayonara Game','Josei/BL','5 (finie)',NULL),
(724,'Sayonara Kyouhansha','Sayonara Kyouhansha','Josei/BL','12 (finie)','-'),
(725,'Season','Season','Josei/BL','5 (finie)','-'),
(726,'Secret Note','Secret Note','Yaoi','5 (finie)',NULL),
(727,'Secret xxx','Secret XXX','Josei/BL','4 (finie)','-'),
(728,'See you later mermaid','See you later mermaid','Shojo/BL','6 (finie)',NULL),
(729,'Seifuku wo Matoeba, Umaku Uso ga Tsuketa no ni','Seifuku wo Matoeba, Umaku Uso ga Tsuketa no ni','Yaoi','6 (finie)',NULL),
(730,'Seirou Opera','La courtisane d''Edo','Shojo','48 (en cours)','-'),
(731,'Sekai de ichiban tooi koi','Sekai de ichiban tooi koi','Josei/BL','Vol 1 (waiting for vol 2)','-'),
(732,'Sekai wa Shippo de Dekiteiru','Sekai wa Shippo de Dekiteiru','Josei/BL','4 (finie)',NULL),
(733,'Sekai wa, Kimi no Toumei','Sekai wa, Kimi no Toumei','Yaoi','12 (en cours?)','-'),
(734,'Sekine-kun no Koi','Sekine-kun no Koi','Josei','32 (finie)','-'),
(735,'Semantic error','Semantic error','Yaoi/Webtoon','76 (en cours)',NULL),
(736,'Sen to Chihiro no kamikakushi','Le voyage de Chihiro','Film','-','film (fini)'),
(737,'Sengoku Night Blood','Sengoku Night Blood','Shojo','-','1 saison (à finir)'),
(738,'Senpai, Danjite Koidewa!','Senpai, Danjite Koidewa!','Josei/BL','Finie','-'),
(739,'Sensei nante Kirai desu','Sensei nante Kirai desu','Josei/BL','7 (finie)',NULL),
(740,'Sensei no Sensei','Sensei no Sensei','Yaoi','6 (finie)',NULL),
(741,'Sensei no Shiroi Uso','Sensei no Shiroi Uso','Seinen','24 (finie)','-'),
(742,'Sensei, Anata ni Chikadukitai','Sensei, Anata ni Chikadukitai','Josei/BL','4 (finie)','-'),
(743,'Sensei, Mou Dame Desu','Sensei, Mou Dame Desu','Shojo/BL','10 (finie)','-'),
(744,'Sex Drop','Sex Drop','Josei/BL','8 (cours)',NULL),
(745,'Shaman King','Shaman King','Shonen','-','1 saison'),
(746,'Shangri la no Tori','Shangri la no Tori','Josei/BL','11 (en cours) VOL2',NULL),
(747,'Shiawase Gohan - Maki to Hanazawa','Shiawase Gohan - Maki to Hanazawa','Shojo/BL','6 (en cours)',NULL),
(748,'Shiawase ni Michita Yoru no Niwa','Shiawase ni Michita Yoru no Niwa','Josei/BL','6 (en cours)',NULL),
(749,'Shigatsu wa Kimi no Uso','Your Lie in April','Shojo','-','1 saison (finie)'),
(750,'Shima-chan Chi no Tsugai Jijou','How My Daddies Became Mates','Josei/BL','11 (en cours)','-'),
(751,'Shimanami Tasogare','Eclat(s) d''âme','Seinen','23 (finie)','-'),
(752,'Shingeki no Kyojin','L''Attaque des Titans','Shonen','139 (finie :( )','3 saisons (4 saison 2020)'),
(753,'Shingetsutan Tsukihime','Tsukihime','Seinen','-','1 saison (finie)'),
(754,'Shinigami wa Korosenai','Shinigami wa Korosenai','Yaoi','6 (finie)',NULL),
(755,'Shinsekai Yori','Shinsekai Yori','Seinen','-','1 saison (finie)'),
(756,'Shounen No Kyoukai','Shounen No Kyoukai','Yaoi','19 (finie)',NULL),
(757,'Shounen to Kamikakushi','Shounen to Kamikakushi','Shojo/BL','7 (finie)','-'),
(758,'Shoushin Otoko ni Haru no Arashi','Shoushin Otoko ni Haru no Arashi','Yaoi','5 (finie)',NULL),
(759,'Shouwa Genroku Rakugo Shinjuu','Le Rakugo à la vie, à la mort','Seinen','-','2 saisons'),
(760,'Shuchuu ni Otoshite Ii desu ka','Shuchuu ni Otoshite Ii desu ka','Joseil/BL','18 (en cours)',NULL),
(761,'Shutline','Shutline','Yaoi/Webtoon','50 (en cours)',NULL),
(762,'Shuumatsu Nani Shitemasu ka? Isogashii desu ka? Sukutte Moratte Ii desu ka?','SukaSuka / What do you do at the end of the world? Are you busy? Will you save us?','Seinen','-','1 saison (finie) LN'),
(763,'Sick','Sick','Josei/BL','6 (finie)','-'),
(764,'Sign','Sign','Yaoi/Webtoon','115 (finie)',NULL),
(765,'Signal','Signal','Shojo/BL','6 (finie)',NULL),
(766,'Simplified Perverted Romance','Simplified Perverted Romance','Yaoi','17 (en cours)',NULL),
(767,'Skip beat','Skip beat','Shojo','309 (en cours)','1 saison (fini)'),
(768,'Slam Dunk','Slam Dunk','Shonen','214 (fini)','1 saison 101 episodes (fini)'),
(769,'Sleeping Dead','Sleeping Dead','Yaoi','5 (en cours)',NULL),
(770,'Smells like green spirit','Smells like green spirit','Josei/BL','14 (finie)','-'),
(771,'Smyrna & Capri','Smyrna & Capri','Yaoi/Webtoon','18 (en cours)',NULL),
(772,'Sono Bijin (Otoko) Fushidara ni Tsuki','Sono Bijin (Otoko) Fushidara ni Tsuki','Josei','3 (en cours)','-'),
(773,'Sono Bisque Doll wa Koi wo Suru','My Dress-Up Darling','Shonen','77 (en cours)','1 saison'),
(774,'Sono Koi wa Ichigo no Youni','Sono Koi wa Ichigo no Youni','Shojo','25 (finie)',NULL),
(775,'Sono Suki Honto','Sono Suki Honto','Josei/BL','4 (finie)',NULL),
(776,'Sore wa Haru no Owari ni','Sore wa Haru no Owari ni','Josei/BL','5.5 (finie)','-'),
(777,'Sore wa Tabun Itoshii tte Koto','Sore wa Tabun Itoshii tte Koto','Josei/BL','5 (finie)','-'),
(778,'Soredemo ai o Chikaimasu ka?','Soredemo ai o Chikaimasu ka?','Josei','62 (en cours)','-'),
(779,'Soredemo, Yasashii Koi o Suru','Soredemo, Yasashii Koi o Suru','Yaoi','6 (finie)',NULL),
(780,'Sorenari ni Shinken Nandesu','Amour Sincère','Josei','13 (fini)','-'),
(781,'Sotsugyousei','Sotsugyousei','Shojo/BL','11 (finie)','-'),
(782,'Speak of the devil','Speak of the devil','Yaoi/Webtoon','54 (en cours)',NULL),
(783,'Spicy Pink','Spicy Pink','Josei','12 (fini)','-'),
(784,'SPY x FAMILY','SPY x FAMILY','Shonen','72 (en cours)','-'),
(785,'Stand my héroes','Stand My Heroes: Piece of Truth','Harem inversé','-','1 saison (finie)'),
(786,'Stay gold','Stay gold','Shojo/BL','35 (finie)',NULL),
(787,'Steins,Gate','Steins,Gate','Seinen','-','1 (saison)'),
(788,'Stigma','Stigma','Yaoi/Webtoon','62 (finie)',NULL),
(789,'Stigmata - Aikon','Stigmata - Aikon','Yaoi','12 (finie)',NULL),
(790,'Stigmata - Seikon Sousa','Stigmata - Seikon Sousa','Yaoi','6 (finie)',NULL),
(791,'Stranger than friends','Stranger than friends','Yaoi/Webtoon','51 (en cours)',NULL),
(792,'Stray Bullet Baby','Stray Bullet Baby','Yaoi','6 (finie)',NULL),
(793,'Suenaga Yoroshiku Onegaishimasu','Suenaga Yoroshiku Onegaishimasu','Shojo','10 (en cours)','-'),
(794,'Suki ni Nacchau yo.','Suki ni Nacchau yo.','Yaoi','6 (finie)',NULL),
(795,'Suki ni Nattara Dame desu ka?','Suki ni Nattara Dame desu ka?','Shojo/BL','6 (finie)','-'),
(796,'Suki, Dakara Furetai','Suki, Dakara Furetai','BL','5 (finie)','-'),
(797,'Sukitte ii na yo.','Say, "I Love You".','Shojo','-','1 saison (finie)'),
(798,'Surge Looking For You','Surge Looking For You','Yaoi/Webtoon','48 (en cours)',NULL),
(799,'Sutenaide my hero','Sutenaide my hero','Yaoi','7 (finie)',NULL),
(800,'Sweet not sugar','Sweet not sugar','Yaoi/Webtoon','14 (en cours)',NULL),
(801,'Switch Girl','Switch Girl','Shojo','Tome 4','-'),
(802,'Tadaima, Okaeri','Tadaima, Okaeri','Shojo/BL','Vol 5 (3.2)',NULL),
(803,'Taishou Otome Otogibanashi','Taishou Otome Otogibanashi','Shojo','-','1 saison (en cours)'),
(804,'Taiso Samurai','The Gymnastics Samourai','Serie animé','-','1 saison (en cours)'),
(805,'Taiyou no le','La Maison du Soleil','Shojo/Josei','50 (finie)','-'),
(806,'Taka ga Fukuen','Taka ga Fukuen','Josei/BL','6 (finie)',NULL),
(807,'Takane & Hana','Takane to Hana','Shojo','101 (finie)','-'),
(808,'Takane no Hana wa Chirasaretai','Takane no Hana wa Chirasaretai','Josei/BL','10 (finie)',NULL),
(809,'Takara no Biidoro','Takara no Biidoro','Yaoi','7 ( finie)',NULL),
(810,'Take to Kota to Aoto','Take to Kota to Aoto','Yaoi','5 (finie)',NULL),
(811,'Tamayura','Tamayura','Josei/BL','5 (finie)','-'),
(812,'Tameiki no Haru ni Koi no Natsu','Tameiki no Haru ni Koi no Natsu','Josei/BL','5 (finie)',NULL),
(813,'Taming the tiger','Taming the tiger','Yaoi/Webtoon','81 (finie)',NULL),
(814,'Tant que nous serons ensemble','Saraba, Yoki Hi`','Josei','24 (en cours)','-'),
(815,'Tasogare Outfocus','Twilight Outfocus','Josei/BL','7 (finie)','-'),
(816,'Te wo Nobashitara, Tsubasa','Te wo Nobashitara, Tsubasa','Yaoi','3 (en cours)',NULL),
(817,'Teacher''s Pet','Teacher''s Pet','Shojo/BL','6 (finie)','-'),
(818,'Tenchi Souzou Design-bu','Heaven''s Design Team','Comedie','-','4 (en cours)'),
(819,'Tenjite Koi to Iki','Born to Love You','Shojo/BL','5 (finie)',NULL),
(820,'Tenkū no shiro Rapyuta','Le château dans le ciel','Film','-','film (fini)'),
(821,'Tenshi Dattara, Yokatta','Tenshi Dattara, Yokatta','Shojo','12 (finie)','-'),
(822,'Tenshi Nanka ja Nai','Je ne suis pas un ange','Shojo','39 (en cours)','-'),
(823,'Terraformars','Terraformars','Seinen','-','1 saison'),
(824,'The Alpha''s Bride','The Alpha''s Bride','Yaoi','21 (en cours)',NULL),
(825,'The Dog Will Not Give Up Unrequited Love','The Dog Will Not Give Up Unrequited Love','Josei/BL','6 (finie)',NULL),
(826,'The Good teacher','The Good teacher','Yaoi/Webtoon','40 (finie)',NULL),
(827,'The Honest Life of a Game Studio','The Honest Life of a Game Studio','Yaoi','1 (en cours)',NULL),
(828,'The insatiable man','The man who can''t taste','Yaoi/Webtoon','51 (en cours)',NULL),
(829,'The Omega Takes a Husband','The Omega Takes a Husband','Yaoi','5 (finie)',NULL),
(830,'The origin of Species','The origin of Species','Yaoi/Webtoon','53 (en cours)',NULL),
(831,'The Pawn''s Revenge','The Pawn''s Revenge','Yaoi/Webtoon','50 (en cours)',NULL),
(832,'The Prefect''s Private Garden','The Prefect''s Private Garden','Josei/BL','vol 3 11 ( suivie)',NULL),
(833,'The song of Yoru and Asa','The song of Yoru and Asa','Yaoi','1 tome (finie)',NULL),
(834,'The Teijo Academy','The Teijo Academy','Josei/BL','Vol3 finie (en cours)',NULL),
(835,'Therapy Game','Therapy Game','Josei/BL','7 (finie)','-'),
(836,'Therapy game Restart','Therapy Game Restart','Josei/BL','11 /19 au japon(en cours)','-'),
(837,'Thermae Romae','Thermae Romae','Seinen','1 saison',NULL),
(838,'Thirst','Thirst','Yaoi/Webtoon','55 (en cours)',NULL),
(839,'To Dear, My Sorrow','To Dear, My Sorrow','Josei/BL','6 (finie)',NULL),
(840,'Tokyo Ghoul','Tokyo Ghoul','Shonen','-','3 saisons (finie)'),
(841,'Tokyo in April','Tokyo in April','Josei/BL','10 (finie)','<3'),
(842,'Tokyo Revengers','Tokyo Revengers','Shonen','196 (en cours)','1 saison (en cours)'),
(843,'Tokyo Tarareba Musume','Tokyo Tarareba Girls','Josei','Vol 9 Act 29 (finie)','-'),
(844,'Tomodachi engagement','Tomodachi engagement','Yaoi','6 (en cours)',NULL),
(845,'Tomodachi Ijou no Koto, Shitai.','Tomodachi Ijou no Koto, Shitai.','Josei/BL','6 (finie)','-'),
(846,'Tonari no Kaibutsu-kun','Le Garçon d''à côté','Shojo','-','1 saison (finie)'),
(847,'Tonari no Metaller-san','Tonari no Metaller-san','Josei/BL','6 (finie)','-'),
(848,'Tonari no Totoro','Mon voisin Totoro','Film','-','film (fini)'),
(849,'Tonari no Usotsuki','Tonari no Usotsuki','Josei/BL','5 (finie)','-'),
(850,'Tonikaku Kawaii','TONIKAWA: Over the Moon For You','Shonen','-','en cours'),
(851,'Too bad, I''m in Love!','Chikyuu no Owari wa Koi no Hajimari','Shojo','20 (finie)','-'),
(852,'Toradora!','Toradora!','Shojo','-','1 saison (finie)'),
(853,'Torokeru Tamago to Bed no Naka de','Torokeru Tamago to Bed no Naka de','Josei/BL','6 (finie)','-'),
(854,'Totsugimasen kara!','Totsugimasen kara!','Shojo/BL','6 (finie)',NULL),
(855,'Toumei na Ai no Utsuwa','Toumei na Ai no Utsuwa','Yaoi','4 (en cours)',NULL),
(856,'Tounan Kadoheya Kare No Koi','Tounan Kadoheya Kare No Koi','Yaoi','6 (finie)',NULL),
(857,'Tourou no Ori','Tourou no Ori','Josei/BL','21 (en cours)','-'),
(858,'Trigun','Trigun','Seinen','-','1 saison (finie)'),
(859,'Tsubaki-chou Lonely Planet','Tsubaki-chou Lonely Planet','Shojo','77 (finie)',NULL),
(860,'Tsuiraku JK to Haijin Kyoushi','Le jeu de la mort','Shojo','89 (en cours)','-'),
(861,'Tsuki no Ura wo Koete: Omegaverse','Tsuki no Ura wo Koete: Omegaverse','Yaoi','6 (finie)',NULL),
(862,'Tsukiattenai Noni Fuufu Yattemasu','Tsukiattenai Noni Fuufu Yattemasu','Shojo/BL','6 (finie)','-'),
(863,'Tsumari Suki tte iitai n dakedo','Agent of my heart','Shojo','9 (en cours)','-'),
(864,'Tsume to Toge','Tsume to Toge','Josei/BL','6 (finie)','-'),
(865,'Tsunaida Koi no Kanaekata','Tsunaida Koi no Kanaekata','Josei/BL','6 (finie)',NULL),
(866,'Two Sides of the Same Coin','Two Sides of the Same Coin','Yaoi','2 tome (finie)',NULL),
(867,'Uchi no bocchama ga kawaikunai','Uchi no bocchama ga kawaikunai','Josei/BL','11 (en cours)','-'),
(868,'Udagawachou de Mattete yo','Udagawachou de Mattete yo','Josei/BL','7 (fine)',NULL),
(869,'Umi de Hirotta ni Sasagu','Umi de Hirotta ni Sasagu','Yaoi','1 (en cours)',NULL),
(870,'Umi ga kikoeru','Je peux entendre l''océan','Film','-','film (fini)'),
(871,'Umi To Futari No Enbun Noudo','Umi To Futari No Enbun Noudo','Josei/BL','6 (finie)',NULL),
(872,'Umibe no etranger','Umibe no etranger','Shojo/Boy''s Love','4 (fini vol 1)','OAV (2020?)'),
(873,'Under My Skin','Under My Skin','Josei/BL','6 (finie)',NULL),
(874,'Under the green light','Under the green light','Yaoi/Webtoon','37 (en cours)',NULL),
(875,'Underskin','Underskin','Josei/BL','5 (finie)','-'),
(876,'Unmei Ja Nai Hito','Unmei Ja Nai Hito','Yaoi','5 (finie)',NULL),
(877,'Unmei no Hito','Unmei no Hito','Joseil/BL','7 (finie)',NULL),
(878,'Unmei no Hito ni Deau Hanashi','Unmei no Hito ni Deau Hanashi','Shojo','13 (en cours)','-'),
(879,'Unmei no Kisu wa Oazuke','Unmei no Kisu wa Oazuke','Yaoi','5 (finie)',NULL),
(880,'Unmei no Tsugai ga Omae da Nante','Unmei no Tsugai ga Omae da Nante','Yaoi','8 (finie)',NULL),
(881,'Unromantic','Unromantic','Yaoi/Webtoon','54 (finie)',NULL),
(882,'Until I Meet My Husband','Until I Meet My Husband','Shojo/BL','12 (finie)',NULL),
(883,'Uramichi Oniisan','Uramichi Oniisan','Seinen','35 (en cours)','-'),
(884,'Uruwashi No Yoi No Tsuki','Uruwashi No Yoi No Tsuki','Shojo','24 (en cours)',NULL),
(885,'Usagi drop','Un drôle de père','Seinen','56,06 (fini)','1 saison (finie)'),
(886,'Usagi no Mori','La fôret aux lapins','Yaoi','Vol 3 chap 14 (en cours)',NULL),
(887,'Utsukushii Koto','Utsukushii Koto','Josei/BL','LN (finie)',NULL),
(888,'Utsukushii Tamashii','Utsukushii Tamashii','Joseil/BL','7 (en cours )',NULL),
(889,'Uzaki-chan wa Asobitai!','Uzaki chan wants to hang out','Seinen','87 (en cours)','1 saison (2 saison 2021)'),
(890,'Uzumaki','Uzumaki','Seinen','1 tome (finie)',NULL),
(891,'Vagabond','Vagabond','Seinen','327 VOL 37 (en cours) Vol 30 chap 162/185p.14/208/209/210/296/301','-'),
(892,'Vampire Knight','Vampire Knight','Shojo','-','2 saisons (finie)'),
(893,'Vanitas no Carte','Les Mémoires de Vanitas','Shonen','-','2 saison'),
(894,'Violet Evergarden','Violet Evergarden','Josei','-','1 saison (+OAV)'),
(895,'Void','Void','Josei/BL','6 (finie)','-'),
(896,'Wagamama mo Kimi no Tame Nara Ikura Demo','Wagamama mo Kimi no Tame Nara Ikura Demo','Yaoi','8 (finie)',NULL),
(897,'Walk on water','Walk on water','Yaoi/Webtoon','62 (finie)',NULL),
(898,'Warau Oni ni wa Fuku Kitaru','Good Fortune Comes to the Demon Who Smiles','Shojo/BL','16 (finie)','-'),
(899,'Watashi No koto Wo Oboete Imasu Ka','Do you still remember me?','Josei','14 (en cours)','-'),
(900,'Watashi no Shiawasena Kekkon','My Blissful Marriage','Josei','23 (en cours)','-'),
(901,'Watashi No Tadashî','Watashi No Tadashî','Seinen','16 (finie)','-'),
(902,'WATASHITACHI WA DOUKA SHITEIRU','Something''s wrong with us','Josei','73 (finie)',NULL),
(903,'Ways of Parting','Ways of Parting','Yaoi/Webtoon','65 (finie)',NULL),
(904,'Wet Sand','Wet Sand','Yaoi/Webtoon','19 (en cours)',NULL),
(905,'When the killer falls in love','When the killer falls in love','Yaoi/Webtoon','50 (en cours)',NULL),
(906,'Wolf''s Rain','Wolf''s Rain','Seinen','-','1 saison (finie)'),
(907,'Wonder Border','Wonder Border','Yaoi','5 (finie)',NULL),
(908,'Wotaku ni Koi wa Muzukashii','Otaku Otaku','Shojo/Josei','86 (finie)','1 saison (finie)'),
(909,'xxxHOLIC','xxxHOLIC','Seinen','manga à partir 185','2 saisons (finie)'),
(910,'Yahari Ore no Seishun Love Come wa Machigatteiru','My Teen Romantic Comedy SNAFU','Seinen/Light Novel','-','3 saisons'),
(911,'Yajirushi','Yajirushi','Josei/BL','6 (finie)','-'),
(912,'Yakusoku no Neverland','The promised neverland','Shonen','52 (à continuer)','1 saison (2 saison 2021)'),
(913,'Yamada-kun to Lv999 no Koi wo Suru','Yamada-kun to Lv999 no Koi wo Suru','Seinen','93 (en cours)',NULL),
(914,'Yamanai Fukou no Owarase Kata','Yamanai Fukou no Owarase Kata','Josei/BL','5 (Finie)','-'),
(915,'Yarichin bitch club','Yarichin bitch club','Josei/BL','23 (en cours)','OAV (finie)'),
(916,'Yatamomo','Yatamomo','Josei/BL','10 (finie)','-'),
(917,'Yesterday wo Utatte','Sing yesterday for me','Seinen','-','1 saison (finie)'),
(918,'Yoake no Uta','Yoake no Uta','Yaoi','15 (en cours)',NULL),
(919,'Yoi yoi monologue','Yoi yoi monologue','Yaoi','6 (finie)',NULL),
(920,'Yondaime Ooyamato Tatsuyuki','Yondaime Ooyamato Tatsuyuki','Josei','8 (fini)','-'),
(921,'Yoru ga Aketemo','Yoru ga Aketemo','Josei/BL','5 (finie)','-'),
(922,'Yoru no Rakka','Yoru no Rakka','Josei','5 (finie)','-'),
(923,'Yoru to Futari','Yoru to Futari','Yaoi','5 (en cours)',NULL),
(924,'Yosuga no Sora','Yosuga no Sora','Seinen','-','1 saison (finie)'),
(925,'Yours to claim','Yours to claim','Yaoi/Webtoon','74 (en cours)',NULL),
(926,'Yozakura Family','Yozakura Family','Shonen','11 (en cours)','-'),
(927,'Yu Yu Hakusho','Yu Yu Hakusho','Shonen','-','(En cours)'),
(928,'Yubisaki to renren','Yubisaki to renren','Shojo','28 (en cours)','-'),
(929,'Yuki no Yōsei','Snow Fairy','Shojo/BL','6 (finie)',NULL),
(930,'Yuki to Matsu','Yuki to Matsu','Seinen','15 (finie)','-'),
(931,'Yukibana no Tora','Le tigre des neiges','Seinen','Vol 3 (en cours)','-'),
(932,'Yukidoke no Koi','Yukidoke no Koi','Josei/BL','7 (finie)',NULL),
(933,'Yukimura-sensei to Kei-kun','Yukimura-sensei to Kei-kun','Josei/BL','8 (finie)','-'),
(934,'Yume Nara Doko Made Yurusaremasuka','How Far Is My Dream Allowed?','Josei/BL','5 (en cours)','-'),
(935,'Yuragi-sou no Yuuna-san','Yuna de la pension Yuragi','Shonen','-','4 (à finir)'),
(936,'Yuri!!! on Ice','Yuri!!! on Ice','Serie animé','-','1 saison (finie)'),
(937,'Yuukoku no Moriarty','Moriarty the Patriot','Shonen','-','7 (en cours)'),
(938,'Yuuutsu na Asa','Blue Morning','Josei/BL','45 (finie)','-'),
(939,'Zankoku na Kami ga Shihai suru','Zankoku na Kami ga Shihai suru','Seinen','86 (finie)',NULL),
(940,'Zanzou Slow Motion','Zanzou Slow Motion','Josei/BL','7 (finie)','-'),
(941,'Ze','Ze','Yaoi','12 (en cours)','-'),
(942,'Zero at the bone','Zero at the bone','Yaoi/Webtoon','24 ( finie)',NULL),
(943,'Zetsubou ni Nake','Zetsubou ni Nake','Josei/BL','7 (finie)',NULL),
(944,'Zoku Pornographer Playback','Zoku Pornographer Playback','Josei/BL','6 (finie)','-'),
(945,'Zombie loan','Zombie loan','Shonen','80 (finie)','1 saison (finie)'),
(946,'α Demo Ω Demo Nai Boku-tachi wa','α Demo Ω Demo Nai Boku-tachi wa','Yaoi','15 (en cours)',NULL),
(947,'Golden Sparkle','Golden Sparkle','Yaoi','5 (finie)',NULL),
(948,'Onward','Onward','Yaoi/Webtoon','28 (en cours)',NULL),
(949,'The Pizza Delivery Man and The Gold Palace','The Pizza Delivery Man and The Gold Palace','Yaoi/Webtoon','39 (en cours)',NULL),
(950,'The literature boy','The literature boy','Yaoi/Webtoon','35 (en cours)',NULL),
(951,'Please Love Me','Please Love Me','Yaoi/Webtoon','9 (finie)',NULL),
(952,'My dear agent','My dear agent','Yaoi','8 (finie)',NULL),
(953,'Loss Time ni Hanamuke o','Loss Time ni Hanamuke o','Yaoi','6 (finie)',NULL),
(954,'Work Love Balance','Work Love Balance','Yaoi/Webtoon','9 (en cours)',NULL),
(955,'Again','Again','Yaoi/Webtoon','58 (en cours)',NULL),
(956,'Bane of my existence','Bane of my existence','Yaoi/Webtoon','sides (finie presque)',NULL),
(957,'No Love Zone','No Love Zone','Yaoi/Webtoon','37 (en cours)',NULL),
(958,'Butler','Butler','Yaoi/Webtoon','sides (finie presque)',NULL),
(959,'Nakaseteyaruyo Yankee-kun','Nakaseteyaruyo Yankee-kun','Yaoi','5 (finie)',NULL);
