BEGIN;

DROP TABLE IF EXISTS "user",
"bd",
"tag";


CREATE TABLE IF NOT EXISTS "user" (
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"    TEXT NOT NULL,
    "email"       TEXT NOT NULL,
    "password"    TEXT NOT NULL,
    "role"        TEXT NOT NULL,
    "created_at"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamptz
);

CREATE TABLE IF NOT EXISTS "bd" (
    "id"    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" TEXT NOT NULL,
    "original_title" TEXT NOT NULL,
    "format" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "author" TEXT NOT NULL,
    "image"  TEXT NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz
);

CREATE TABLE IF NOT EXISTS "tag" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" TEXT NOT NULL,
  "color" TEXT NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);


CREATE TABLE IF NOT EXISTS "bd_has_tag" (
  "bd_id" INTEGER NOT NULL REFERENCES "bd"("id"),
  "tag_id" INTEGER NOT NULL REFERENCES "tag"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz,
  PRIMARY KEY (bd_id, tag_id)
  );


COMMIT;