DROP TABLE "user";

CREATE TABLE IF NOT EXISTS "role" (
    "id"      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"    TEXT NOT NULL,
    "created_at"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamptz
);

CREATE TABLE IF NOT EXISTS "user" (
    "id"          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username"    TEXT NOT NULL,
    "email"       TEXT NOT NULL,
    "password"    TEXT NOT NULL,
    "role_id"     INTEGER NOT NULL REFERENCES "role"("id"),
    "created_at"  timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at"  timestamptz
);



INSERT INTO "role" ("id", "name") VALUES
(1, 'user'),
(2, 'admin');


INSERT INTO "user" ("id", "username", "email", "password", "role_id") VALUES
(1, 'gintoki', 'gintoki-sakata@email.com', '$2b$10$7vwYGrz2TGeyG4X8YnD9BOag9I.YKGUTJELs64qGmcK/syHu2BzTG', 1),
(2, 'mongolian-chop-squad', 'beck@email.com', '$2b$10$7vwYGrz2TGeyG4X8YnD9BOag9I.YKGUTJELs64qGmcK/syHu2BzTG', 1);



